### ISSUE TITLE
al-ctrl and coffeescript classes

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#113]
Hi,

earlier before i was able to use

``` coffeescript
class MyController
  constructor: (@scope) ->
    @myVar = 'Hello World'

alight.controllers['MyController'] = MyController
```

and

``` html
<div data-al-controller="MyController as myCtrl1">
</div>
```

to register coffeescript classes (see https://github.com/lega911/angular-light/issues/51).

Now i need to write

``` coffeescript
class MyController
  constructor: (@scope,@cd) ->
    @myVar = 'Hello World'

alight.ctrl.mycontroller = (scope, cd) ->
  scope.myControllerInstance = new MyController(scope,cd)
```

and

``` html
<div data-ctrl-mycontroller="">
</div>
```

to achieve a similiar (not the _same_!) functionality.

Is there another, better approach to integrate coffeescript classes for the new alight version?
I would like to create the instance implicitly in the DOM as i did before.
Another problem of the new approach: when i want to access myVar, i need to define the access to the instance explicitly:

``` html
<div data-ctrl-mycontroller="">
  {{myControllerInstance.myVar}}
</div>
```

I would like to see an approach to rewrite the scope automatically to achieve something like this, but unfortunately this seems not to work:

``` coffeescript
class MyController
  constructor: (@scope,@cd) ->
    @myVar = 'Hello World'

alight.ctrl.mycontroller = MyController
```

``` html
<div data-ctrl-mycontroller="">
  {{myVar}}
</div>
```

**Comment by lega911** [comment]
Hello!
Here is a test version 0.12, http://angularlight.org/bin/alight_0.12.last.debug.js
I brought back al-controller as al-ctrl="MyController" for functions and al-ctrl="@MyController" for classes, you can propose better API for this

example: http://jsbin.com/bigexok/2/edit?html,js,output
Also you can join chat: https://gitter.im/lega911/angular-light

**Comment by lega911** [comment]
Fix, al-ctrl="MyController" now works for classes and functions, it checks prototype

example: http://jsbin.com/bigexok/edit?html,js,output

**Comment by dev-rke** [comment]
Wow, looks very good. :-)
I'll give it a try on monday with my application.

**Comment by dev-rke** [comment]
Seems to work. :-)
When 0.12 stable will be released?

**Comment by lega911** [comment]
This week or next one, I need to improve filters and make a couple of unit-tests.

I want to simplify filters, look at this example https://gist.github.com/lega911/09a75ea343523013b525
What do you think about "new style", do they look better? Do you have any ideas about filters?

**Comment by lega911** [comment]
version 0.12 is almost ready: http://angularlight.org/bin/alight_0.12.last.debug.js
example for "new" filters: http://jsfiddle.net/lega911/as3oyoq4/
