### ISSUE TITLE
node.js templating support?

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#119]
Hi,

i am thinking about if it would be useful to have some templating support for node.js.
E.g. for the al-repeat directive the resulting values could get pre-generated, so search engines and screen readers could fetch the data easier.
A huge issue for search engines and other crawlers is that they do not interpret javascript, even if google has some basic support for it (e.g. html5 history states).
So there is some need to pre-render pages when crawlers enter them.
It would be more simple if one doesn't need not define multiple templates for this, so it would be great if some basic node.js templating support (e.g. as an additional project) would be added. Currently this would be possible using phantom.js, but i assume this also would be slow.

What do you think about? 
Do you have some ideas how this issue could be solved in a clean and fast approach?

**Comment by lega911** [comment]
Can you make a sample how it could be?
What if I have jQuery directives inside of al-repeat loop? It's difficult path.

1) I think, the easies way is phantom.js + caching pages, then it will be fast, a cache is faster than virtual dom.
2) You can try to write a text on a page into an invisible div, then google can read it.

Probably you need a site instead of SPA, so you can build a site with AL widgets.

**Comment by dev-rke** [comment]
Yeah i know these directives which depend on DOM access.
1) is bad if you have often changing data, e.g. a news portal
2) is also bad, due to redundant content, when the application fetches data e.g. using ajax. Especially for screen readers and also for modern search engines which interpret JS
3) using widgets e.g. to display data might work, but support of alight needs to be improved:
If you need something like a sliding carousel (e.g. for images which should rotate) there is no directive which would allow developing something like this with low effort. Currently you would define an al-repeat and render the images inside, using al-animate and al-click to toggle to the next slide. An SEO-useful way would be to render all slides, fetch the data from the DOM (e.g. using data attributes) and then render the slides. But currently you need to define custom directives to achieve this. What i think about is some general directive, which allows reading data structures from DOM content, so scope variables will be updated from the DOM. Currently only data structures from scope variables will be put to DOM not vice versa.
Example:

``` javascript
scope.myScopeVariable = [1,2,3,4]
```

``` html
<ul al-repeat="x in myScopeVariable">
  <li>{{x}}</li>
</ul>
```

What i think about is to define content using a server side templating engine, read this content into a scope variable and have the possibility to modify the scope variable so content will be changed.
Example:

``` javascript
scope.myScopeVariable = []
```

``` html
<ul al-repeat="x in myScopeVariable" al-fetchdata="true">
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
</ul>
```

After initialization finished the scope variable looks like:

``` javascript
scope.myScopeVariable = [1,2,3,4]
```

Would it be possible to define some html comments or something like that to define a template which will be used to fetch data from a DOM structure?
E.g. like

``` html
<ul al-repeat="x in myScopeVariable">
  <!-- al-fetchdata: <li>{{x}}</li> -->
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
</ul>
```

The al-fetchdata directive will parse the given data structure and so it can understand how to parse the data.
An more complex example:

``` html
<ul al-repeat="x in myScopeVariable">
  <!-- al-fetchdata: <li><a href="{{x.url}}">{{x.name}}</a></li> -->
  <li><a href="/1">1</a></li>
  <li><a href="/2">2</a></li>
  <li><a href="/3">3</a></li>
  <li><a href="/4">4</a></li>
</ul>
```

which should result in

``` javascript
scope.myScopeVariable = [
  {url: "/1", name: "1"},
  {url: "/2", name: "2"},
  {url: "/3", name: "3"},
  {url: "/4", name: "4"}
]
```

Do you think this would be helpful and technically possible?
By the way: i did not understand what you mean with the word "SPA" in your comment.

**Comment by lega911** [comment]
> a news portal

Why often? A news usually is not modified since it was written. So you need call phantomjs only once for one article.
If you have any frequent changes (e.g. comments), you can inject them before sending, so you can use old cache.
Also you can exclude comments (maybe google doesn't need them).
Also you can use prerender.io
Anyway it's one of the easiest ways.

Your examples have a mistake: al-repeat should be in "li", not in "ul", will you put al-repeat in the first "li"-element or in everyone?

> directive, which allows reading data structures from DOM content, so scope variables will be updated from the DOM

Firstly, it will not be able to read hidden parts from "al-if",
second - you don't need it, you can put ready json near by, e.g.

```
<!-- DATA
scope.myScopeVariable = [
  {url: "/1", name: "1"},
  {url: "/2", name: "2"},
  {url: "/3", name: "3"},
  {url: "/4", name: "4"}
]
-->
<ul al-repeat="x in myScopeVariable">
  <li><a href="/1">1</a></li>
  <li><a href="/2">2</a></li>
  <li><a href="/3">3</a></li>
  <li><a href="/4">4</a></li>
</ul>
```

> Do you think this would be helpful and technically possible?

I've already thought about it. You can't cover all directives, there are a lot of work and it it difficult to use, a lot of limitations. So I think no one will use it.
Yes we can make a template-engine, that will support a few directives, but it will be useless. I usually make manual directives and filters, I use text-directives, I can extend directives (hooks) and so on, also jQuery is used in 90% web projects.

We can try to integrate a virtual-dom for server-rendering, but anyway it will give us the complexity and limitations.

SPA - Single Page Application, it's like GMail (asana, personal todo-lists etc), where you don't need seo (you can't find your mails in google).
On the other hand - sites, like github*, it has server-rendering, and also it has a lot ajax widgets.

**Comment by dev-rke** [comment]
> A news usually is not modified since it was written.

Yes, for small news pages this might work. For heavy accessed news pages, where multiple crawlers access multiple times per minute this might work, but i don't like it.

> prerender.io

I didn't know this, thanks. As i _have to_ use PHP in my job, i am not able to use phantomjs.
But prerender.io offers an apache ruleset, i think this should be a possible solution.

> you can put ready json near by

This won't work. Hidden and dynamic content is not interpreted by most crawlers (except google - but only partially).

> You can't cover all directives, there are a lot of work and it it difficult to use, a lot of limitations.

Yes, but i talk to you to find some good solution for this issue together. :-)

> Yes we can make a template-engine, that will support a few directives, but it will be useless

What i think about is how i could display content which is visible when someone access the page with disabled javascript or a search engine crawler. This content has to hide if someone has enabled javascript.
I just found a way how to exclude some page content from google: https://perishablepress.com/tell-google-to-not-index-certain-parts-of-your-page/
Just an idea, a simple solution might be this:

``` html
<ul>
  <li al-hide="true">1</li>
  <li al-hide="true">2</li>
  <li al-hide="true">3</li>
  <!--googleoff: index-->
  <li al-repeat="x in myScopeVariable">{{x}}</li>
  <!--googleon: index>
</ul>
```

or as plain and ugly php template:

``` php
<ul>
  <?php foreach(myScopeVariable as x) ?>
    <li al-hide="true"><?php echo x; ?></li>
  <?php endforeach; ?>
  <!--googleoff: index-->
  <li al-repeat="x in myScopeVariable">{{x}}</li>
  <!--googleon: index>
</ul>
```

By default the list with 1,2,3 will be rendered. If JS is enabled, 1,2,3 will be hidden and then the al-repeat renders the value. :-)
The good thing is, the content will be rendered by the server. 
The ugly thing is, you have to implement the rendering twice.
But i like this approach!
Do you mind to put this in the docs as faq entry?

> jQuery is used in 90% web projects

I would assume 98%. I do not like jQuery, because it is ugly and fat. But i have no choice, because very much developers depend on this old and stable lib. 95% of daily method usage has been implemented into the browsers and can be used without jQuery. But the developers still prefer this slow and fat lib.

> you can't find your mails in google

You can find your own mails, but I can't find your mails. ;-)

**Comment by lega911** [comment]
> This won't work. Hidden and dynamic content is not interpreted by most crawlers

crawlers will take data from html (ul-li) that you make with PHP. AL will take json data that will be near by

> or as plain and ugly php template:

Also you can do like this:

``` html
<ul al-hide="true">
  <li>1</li>
  <li>2</li>
  <li>3</li>
</ul>
<!--googleoff: index-->
<ul>
  <li al-repeat="x in myScopeVariable">{{x}}</li>
</ul>
<!--googleon: index-->
```

> Do you mind to put this in the docs as faq entry?

Why not. You can fix docs, if you have what to write, https://github.com/lega911/alight_docs

**Comment by dev-rke** [comment]
Ok, i think we can close this issue.
The solution to hide prerendered content as content fallback is ok for small usage on typical web pages.
If a more accurate prerendering is needed prerender.io should fulfill the requirements.
