### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by nzmedet** [lega911/angular-light#12]
- `$http` is great service (provider), and very useful, could you add it there? So directives can easily fetch data from outside
- `controller` for directive

``` js
    alight.directives.al.test = {
        restrict: 'E',
        template: '<b>asd{{test.val}}</b>',
        link: function(){
            console.log(arguments);
        },
        controller: function($http){
            console.log(arguments);
            var vm = this;
                $http.get('url').then(function(){
                      vm.val = "qwe";
                });
        },
        controllerAs: 'test'
    };
```

Indeed that's all for complete self contained directive.

**Comment by erickskrauch** [comment]
$http is default for Angular, but aLight is cool, because you can make this service as you and you project needed.

But I think it would be cool if other developers would develop and publish a variety of modules and extensions for the library. Thus you will be able to collect only the necessary parts.

**Comment by nzmedet** [comment]
totally agree, but it's a coffeescript :cry:

**Comment by erickskrauch** [comment]
But no one forces you to write your controllers/directives on coffescrept.

**Comment by lega911** [comment]
You can append controller for self, example: http://plnkr.co/edit/txA6N8H7pjUNtIqduzLa?p=preview
Instead of $http, you can use jQuery.get/post

**Comment by nzmedet** [comment]
Awesome, that's it, for  15kb. But could you name it more readable
`alight.directives.al.test` why al? why not `alight.directives.test`
Oops. it's now `48,2 KB`, 320% increase

**Comment by lega911** [comment]
It's like a namespace, al-click, ui-datetime.
If you attach library "ui", it can make namespace "ui" (alight.directives.ui = {}).
After that, if you write `<div ui-datetime></div>`, and there is no ui.datetime, then AL will throw error "no ui-datetime".

**Comment by lega911** [comment]
> it's now 48,2 KB, 320% increase

15kb gzipped ~= 48kb raw, it means server transfers 15kb to your browser.

**Comment by vko-online** [comment]
Oh God, `http://angularlight.org/bin/alight_0.8.4.min.js` this file is 48kb and yes, it's really minified

**Comment by lega911** [comment]
> this file is 48kb and yes, it's really minified

Look at network panel, what size was is real transferred.

> Instead of $http, you can use jQuery.get/post

If you don't want attach jQuery, you can use [this code](http://youmightnotneedjquery.com/#request)
or you can use built-in alight.f$.ajax

**Comment by nzmedet** [comment]
Oh, thanks, didn't know that minified file can also be gziped, great.

**Comment by nzmedet** [comment]
This project deserves MORE STARS!

**Comment by lega911** [comment]
Thanks.
