### ISSUE TITLE
Ajax not working in 0.12.3

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#125]
Hi,

the ajax method in fQuery seems to be a bit buggy:
https://github.com/lega911/angular-light/blob/master/src/js/fquery.js

``` javascript
f$.ajax = function(args) {
        if(args.username || args.password || args.headers || args.data || !args.cache) return rawAjax(args);
```

should be 

``` javascript
f$.ajax = function(args) {
        if(args.username || args.password || args.headers || args.data || !args.cache) return f$.rawAjax(args);
```

because the rawAjax method is now a method of f$.
I solved this using calling rawAjax instead of ajax, but i think it would be useful to fix this.

**Comment by lega911** [comment]
fixed.
thank you
