### ISSUE TITLE
Example for filter in plain JS

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#126]
Hi,

i need a working example of plain JS to create a new filter.
The current implementation of filters in sourcecode seems to use only coffeescript classes,
but i think this a bit complicated for simple filters in JS.

This example seems not to work anymore:
https://angular-light.readthedocs.org/en/latest/create_filter.html

Could you please give an more up-to-date plain JS example and link it in the docs:
https://jsfiddle.net/lega911/pTT5x/

Thank you. :-)

**Comment by lega911** [comment]
Hello!

jsfiddle on https doesn't accept AL from http, the right link is http://jsfiddle.net/lega911/pTT5x/
but it's example for an old version

there are two ways to make filters - 1) as a simple function: http://jsfiddle.net/lega911/chbysp0a/
2) but if you add a prototype to this function, then it will be used as async filter: http://angular-light.readthedocs.org/en/latest/async_filter.html example http://jsfiddle.net/lega911/ktpoofcp/

I updated examples and append 2 example for JS and examples for TypeScript and CoffeeScript
http://jsfiddle.net/lega911/ktpoofcp/
http://jsfiddle.net/lega911/Lkv0t80v/
http://jsfiddle.net/lega911/tzt2r1na/

**Comment by dev-rke** [comment]
Please could you provide the angularlight sources in the examples from HTTPS?
Same for angularlight.org.
letsencrypt.org provides free certificates, installation is simple and well documented. :-)

Thanks for filter explanation, could you please link them in the docs? :-)

If its not a gag the following typo "trottle" should be corrected to "throttle" in the examples:
https://angular-light.readthedocs.org/en/latest/async_filter.html
https://jsfiddle.net/lega911/ktpoofcp/
In german a "Trottel" is a fool. ;-)
