### ISSUE TITLE
Example for Controllers

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#127]
I also would like to see how the al-ctrl directive has to be used.
I understand how to use it with coffeescript, but i had problems using it in plain js, so i recommend to give an example for this directive in the docs.

A simple implementation could look like:

``` javascript
alight.ctrl.main = function(scope) {
  scope.myVar = 123;
}
```

``` html
<div al-app al-ctrl="main">
  {{myVar}}
</div>
```

And as far as i remember i could also concatenate al-app and al-ctrl into `al-app="main"`
this should be noted as well. :-)

**Comment by lega911** [comment]
I made a description with examples: http://angular-light.readthedocs.org/en/latest/controller.html
Is is ok now? What else can I append?

**Comment by dev-rke** [comment]
Great!
Please fix the link of al-ctrl on this page:
https://angular-light.readthedocs.org/en/latest/directive.html
Its target is currently https://angular-light.readthedocs.org/controller.html
and should be your new link. :-)

**Comment by dev-rke** [comment]
Ah, i miss a hint what the scope is in the coffeescript and typescript examles in the new controller docs.
It would be great to read that the scope of a coffeescript class is the prototype of the class (same for typescript) and there also the changeDetector methods @$watch, @$scan @$getValue etc. are available in this class.

I got a question on this: is the class "extended" as i wrote before or will the methods injected into the prototype after creating a new instance? If you "extend" it manually, it might collide with traditional coffeescript class inheritance.

**Comment by lega911** [comment]
fixed, AL clones your class, then append Scope's methods into, then makes an instance

**Comment by dev-rke** [comment]
Great, thank you, this is what a dev would expect.
I'll close this issue.
