### ISSUE TITLE
Improvement: Inheritance for filters

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#128]
Hi,

for my current project i had to copy the default filter "orderBy" and customize it to be case insensitive.
It would be great if filters could be easily extended by overriding existing inherited public methods.
E.g. for the filter "orderBy" the sortFn should be exposed as public method.
This would allow "forking" existing filters and reduce the overhead a user need to implement.
Could this be realized?

I think about this (untested):

``` coffeescript
alight.filters.orderBy = class O
    key: 'key'
    list: null
    direction: 1


    constructor: (exp, scope) ->
        d = exp.split ','

        # key
        if d[0]
            scope.$watch d[0].trim(), (v) ->
                @key = v
                @doSort()

        # reverse
        if d[1]
            scope.$watch d[1].trim(), (v) ->
                @direction = if v then 1 else -1
                @doSort()

    sortFn: (a, b) ->
        va = a[@key].toLowerCase() or null
        vb = b[@key].toLowerCase() or null
        if va < vb
            return -@direction
        if va > vb
            return @direction
        return 0

    doSort: ->
        if @list instanceof Array
            @list.sort @sortFn
            @setValue @list

    # i think here it should a '=>' be used because the event occures from external emitter
    # @see: http://coffeescript.org/#fat-arrow
    onChange: (input) =>
        if input instanceof Array
            @list = input.slice()
        else
            @list = null
        @doSort()
```

This is already patched to make a lowercased compare.

Why is this approach useful?
I can easily extend the existing filter to create inheritance. 
This allows to instantiate a customized child prototype (also untested code):

``` coffeescript
alight.filters.myOrderBy = class P extends alight.filters.orderBy
    # here i can implement my custom sorting function - alight.filters.orderBy should be still working
    sortFn: (a, b) ->
        if a < b
            return -@direction
        if a > b
            return @direction
        return 0
```

And even if one needs to override global behaviour this would be useful (untested code, the third today :-/ ):

``` coffeescript
alight.filters.orderBy::sortFn = (a,b) ->
    # lets do some nonsense
    return 0
```

What do you think?

**Comment by lega911** [comment]
done, example of inheritance: https://github.com/lega911/angular-light/blob/53bde510e005a8342898d72154a2ab9aa3be631e/test/filter/orderby.coffee#L48

**Comment by dev-rke** [comment]
Great, thanks! :-)
