### ISSUE TITLE
Add Scope.$root

### ISSUE THREAD

**Issue by rumkin** [lega911/angular-light#130]
Add root scope access with $parent lookup.

**Comment by lega911** [comment]
What for?
The last version, AL doesn't make extra scopes for al-if, al-include, al-repeat, so your application can have only (root) scope, it means you don't need link to root (from root).

**Comment by rumkin** [comment]
I have custom view directive which produces new scope. Nested views produce nested scopes. In this case it's hard to predict how deep my scope actually is.

**Comment by lega911** [comment]
you can do: `scope.$root = $scope.$parent.$root || $scope.$parent` in your directive

I think storing common data in root is not good way (direct using), probably I would pass it via props:

``` html
<div my-directive="form">
  <div my-directive="value">
    <div my-directive="value"> {{value.name}} </div>
  </div>
</div>
```

``` javascript
root.form.name = 'name';

alight.directives.my.directive = {
  scope: true,
  link: function(scope, _el, key) {
    scope.value = scope.$parent.$getValue(key);
  }
}
```

**Comment by rumkin** [comment]
And than I should to rewrite all directives that doesn't assign `$root`. What's about other's directives which doesn't do this?

Actually a have more cases with real global objects like `location` singleton which should be global to preserve consistency.

**Comment by lega911** [comment]
You can make global service, example: http://plnkr.co/edit/KWPJiGNSKhoOTDZb5p48?p=preview
Example with router/location: http://plnkr.co/edit/QYb53NUnnhIezI5n0JxB?p=preview

I made a hack, that inject $root in every scope: http://jsfiddle.net/lega911/6jeptnr2/

I think it can be helpful to have a tool for extending scope for $root, $emit, $broadcast etc. so I probably will make it.

**Comment by lega911** [comment]
try this: http://jsfiddle.net/lega911/4oc6t76f/
you can add a function to alight.hooks.scope, it will be executed on creating a scope.
now, you can append $root or any other functional.
