### ISSUE TITLE
Rebinding of DOM structures

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#132]
When a alight app is started, is there a best practice to "rebind" DOM structures when they changed?
E.g. when i have to do some jQuery code to inject DOM structures with alight directives, will these alight directives automatically detected or have i to do it manually?

**Comment by lega911** [comment]
AL doesn't observe DOM changes, so you should bind it manually (you can  make an observer for self).

Basically, you can call **alight.bootstrap(element)**, then the element will be bound to a new root-scope (example http://plnkr.co/edit/KjcuZp?p=preview ).
If you have a scope you need to bind to an element, you can call **alight.bind(scope, element)**

docs "a few ways to bind" http://angular-light.readthedocs.org/en/latest/binding_to_dom.html

I can give you an example if you want.

**Comment by dev-rke** [comment]
Yeah, i knew the binding function, just wanted to know if the DOM will be observed for changes.
Thank you. :-)
