### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#135]
I have problems to understand, when and where an error occured.
Might it be possible to track down in which directive / filter / controller an error occured at which specific line?
How to use the debug library?

**Comment by lega911** [comment]
Look at example: http://jsfiddle.net/lega911/r9exL2hc/
When you click on the button, you can see in console:

```
al-click, error in expression: onClick()
 riseAnException is not defined
```

you have a name of directive, an expression, a reason of error
Also you have an element where it happened and scope.
In next line you have a traceback.

I think it's enough to find problems.

Maybe there is a case where you don't have an explanation like this, give me an example of it.

**Comment by dev-rke** [comment]
I use firefox web developer tools, currently in jsfiddle.
Your example works very well, its simple to understand and good to track down.

In my example it is unclear which line of code fired the exception:

```
$scan, error in expression: $parent.$templates.teaser.Test
 $$scope.$parent.$templates.teaser is undefined
 Object { src: "$parent.$templates.teaser.Test", result: Object } alight_0.12.last.min.js:6:24770
19:09:00.981 anonymous@http://angularlight.org/bin/alight_0.12.last.min.js line 6 > Function:1:8
e/f@http://angularlight.org/bin/alight_0.12.last.min.js:6:7469
e/r.prototype.digest@http://angularlight.org/bin/alight_0.12.last.min.js:6:8314
e/e.applyBindings@http://angularlight.org/bin/alight_0.12.last.min.js:6:22754
e/</<.fn@http://angularlight.org/bin/alight_0.12.last.min.js:6:18052
e/</<.fn/t.$init/l@http://angularlight.org/bin/alight_0.12.last.min.js:6:15920
e/</<.fn/t.$init@http://angularlight.org/bin/alight_0.12.last.min.js:6:16249
e/y</<@http://angularlight.org/bin/alight_0.12.last.min.js:6:20978
e/w@http://angularlight.org/bin/alight_0.12.last.min.js:6:21714
e/y</<@http://angularlight.org/bin/alight_0.12.last.min.js:6:21364
e/w@http://angularlight.org/bin/alight_0.12.last.min.js:6:21714
e/e.applyBindings@http://angularlight.org/bin/alight_0.12.last.min.js:6:22619
e/e.d.al.ctrl.link/a.start@http://angularlight.org/bin/alight_0.12.last.min.js:7:19967
e/</<.fn@http://angularlight.org/bin/alight_0.12.last.min.js:6:17945
e/</<.fn/t.$init/l@http://angularlight.org/bin/alight_0.12.last.min.js:6:15920
e/</<.fn/t.$init@http://angularlight.org/bin/alight_0.12.last.min.js:6:16249
e/y</<@http://angularlight.org/bin/alight_0.12.last.min.js:6:20978
e/w@http://angularlight.org/bin/alight_0.12.last.min.js:6:21714
e/e.applyBindings@http://angularlight.org/bin/alight_0.12.last.min.js:6:22619
e/e.bootstrap@http://angularlight.org/bin/alight_0.12.last.min.js:6:23423
anonymous@coffeescript:54:1
CoffeeScript</require["./browser"]</</CoffeeScript.run@https://fiddle.jshell.net/js/coffeescript/coffeescript.js:12:5952
CoffeeScript</require["./browser"]</</runScripts/n@https://fiddle.jshell.net/js/coffeescript/coffeescript.js:12:7293
CoffeeScript</require["./browser"]</</runScripts@https://fiddle.jshell.net/js/coffeescript/coffeescript.js:12:7601
```

The cause of the exception was, that i used a wrong scope variable name in the html template which could not be resolved.
But i dont get an information that the scope variable in the template could not be resolved.
Also the exception "result" object does not give an informtion which DOM node is currently used.
It would be great if the stacktrace would throw which directive throwed the error.
This mostly happens in own directives, default alight directives do not seem to have bigger problems on this. In my production environment i use pre-compiled coffeescript, same problem here.

Do you have some recommendations how to handle this?
I made a simple example: https://jsfiddle.net/r9exL2hc/1/
In this case it is well documented, i can see the correct directive and the correct element.
In more dynamic environments (e.g. with watchers on scope variables) i had more problems to track it down.

Could you please explain why there is a debug library? Which features does it offer?
How to use the debug library?

**Comment by lega911** [comment]
> In my example it is unclear which line of code fired the exception:

I've added scope and element for this case.

> It would be great if the stacktrace would throw which directive throwed the error.

I've thoughts how can I make it, but every improvement makes the lib more heavy and slow*
Now it is 18kb, year ago it was 11kb, so we should pick features carefully

> How to use the debug library?

What are you talking about? Which one lib?

**Comment by dev-rke** [comment]
> > In my example it is unclear which line of code fired the exception:
> 
> I've added scope and element for this case.
> 
> > It would be great if the stacktrace would throw which directive throwed the error.
> 
> I've thoughts how can I make it, but every improvement makes the lib more heavy and slow*
> Now it is 18kb, year ago it was 11kb, so we should pick features carefully

It would be great if this could be provided as debugging library, so a developer can download this if he needs more detailed debug information.

> > How to use the debug library?
> 
> What are you talking about? Which one lib?

On http://angularlight.org/ i can download this two links:
http://angularlight.org/bin/alight_0.12.last.min.js
http://angularlight.org/bin/alight_0.12.last.debug.js

Where is the difference?

**Comment by lega911** [comment]
> Where is the difference?

debug - it's the same, but before uglify

**Comment by fend25** [comment]
@lega911 
how about this renaming?
`alight.debug.js` -> `alight.js`
`alight.js` -> `alight.min.js`

and, of course, save the `alight.debug.js` for jsfiddle compatibility)

it's like a standard for the majority of js libraries and frameworks

**Comment by lega911** [comment]
ok

**Comment by dev-rke** [comment]
Maybe it would be great to link files without version numbers in the fiddles.
So a user can see if the fiddle works with current version. And if a fiddle doesnt work anymore, we get a issue request here to fix it. :-)

**Comment by fend25** [comment]
@dev-rke sounds good, I support

**Comment by lega911** [comment]
> So a user can see if the fiddle works with current version.

or a user will think that AL doesn't work... no one has made an issue on any break example (or I don't remember this)
you can open the list of examples on the site, 80% of examples will not work on the last version, also there are examples that we don't have access to.
I need to allocate a time to update examples.

**Comment by dev-rke** [comment]
Ok, another idea: what about putting some selected examples to a example folder which is included in the alight repository? I would recommend to put multiple examples on one page, e.g. one page for controllers, one page for directives, one page for filters etc.
This would allow to focus on relevant things and it would be easy to update the examples (by yourself, by pull requests or by issue requests).
Examples are nice to have to understand how alight works, but they should work, especially when they are linked in the docs.
This could reduce the time to maintain examples.

Another approach would be to also write unit tests for examples, so even edge cases would be tested by unittests.

**Comment by lega911** [comment]
I think it will take more time than jsfiddle.

the debug library - is a good idea, but I need specifics, what do you want to see there?
Now you can replace alight.exceptionHandler and use it somehow.

**Comment by dev-rke** [comment]
Yes, initially it takes more time to create this.
But over a long time it might be easier to update. :-)

Debug library: as i proposed a full stack trace containing line number would be great.

**Comment by dev-rke** [comment]
After some more development i found out that there nearly all error cases are implemented and the line which produces the error can be found out during development.

But when there are errors in a custom filter, the al-repeat catches this error and re-throws a new, own error.
This is a bit "ugly", because it is unclear that the error occurs in the filter and not in al-repeat.

**Comment by lega911** [comment]
Can you give me an example?

This filter gives me a normal stacktrace to the error: http://jsfiddle.net/lega911/topk3bco/

``` js
alight.js:2456 ReferenceError: ThrowError is not defined
    at alight.filters.ff ((index):50)
    at .<anonymous> (alight.js:545)
    at scanCore (alight.js:835)
    at ChangeDetector.digest (alight.js:887)
    at Object.alight.bind.alight.applyBindings (alight.js:2256)
    at Object.alight.bootstrap (alight.js:2312)
    at Array.alight.bootstrap (alight.js:2273)
    at HTMLDocument.onReady (alight.js:93)
```

**Comment by dev-rke** [comment]
Ok, i think i got it:
https://jsfiddle.net/pur6y34s/

When an exception is thrown (e.g. by another module which is called from a filter), the handling does not serve a stacktrace. I am using Firefox.

Output:

```
$scan, error in expression: 10

Object { src: "10", scope: Object, element: null, result: Object } alight_0.12.last.debug.js:2496:3
test                                            alight_0.12.last.debug.js:2498:10
  buildAlight/alight.exceptionHandler()         alight_0.12.last.debug.js:2498
  buildAlight/ChangeDetector.prototype.digest() alight_0.12.last.debug.js:926
  buildAlight/alight.applyBindings()            alight_0.12.last.debug.js:2298
  buildAlight/alight.bootstrap()                alight_0.12.last.debug.js:2354
  buildAlight/alight.bootstrap()                alight_0.12.last.debug.js:2315
  onReady()
```

**Comment by lega911** [comment]
> the handling does not serve a stacktrace

yes, string doesn't contain stacktrace, you should use Error for this: throw new Error('TEST');
https://jsfiddle.net/lega911/zvwduyzL/

**Comment by dev-rke** [comment]
> yes, string doesn't contain stacktrace, you should use Error for this: throw new Error('TEST');

Thank you, didn't know that.
I think we can close the issue.
