### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by lega911** [lega911/angular-light#142]
http://plnkr.co/edit/1QLX6xXnkVNkaVeDdpUJ?p=preview
http://plnkr.co/edit/1QLX6xXnkVNkaVeDdpUJ?p=preview

``` html
<my-paginator :page="page" @on-left="page--" @on-right="page++"></my-paginator>
```

http://plnkr.co/edit/lM4wwJq28egHIJzS7pTX?p=preview
http://plnkr.co/edit/8jeW3XkkPPE0OTrwcadD?p=preview
http://plnkr.co/edit/BhUwynTHrat6Tm76unTo?p=preview

**Comment by dev-rke** [comment]
Just an idea, didn't think very long about it:
Does it make sense to define the plugin interface as Document Type Definition?
https://en.wikipedia.org/wiki/Document_type_definition#XML_DTD_schema_example

This would enforce the developers to provide an parsable interface and 
would allow auto completion in IDEs for components.
We also could think about to provide a DTD for standard alight element attributes (e.g. al-on or al-select etc.).

For plugin interfaces this would simplify to parse which attributes (e.g. events) an element provides, so a developer can use them directly in the IDE without looking up possible attributes in documentation.

**Comment by dev-rke** [comment]
And i like the component approach, it seems to be very flexible.
Can i "extend" already existing components (e.g. one created a fancy dropdown, may i being able to inherit from that to e.g. customize the standard template)?

**Comment by lega911** [comment]
> Can i "extend" already existing components

Now, a component - is a simple function which returns an object {template, props, ...}, so if you want to inherit it, you need to call that function (component) and change a result which it returns.

It's a prototype of "component", you can propose better API/style.

**Comment by dev-rke** [comment]
May it be useful to force developers to define an object or an prototype as "component" instead of a function to achieve this?
I am not sure if that would be good.

**Comment by lega911** [comment]
Maybe, we can use classes for this.

**Comment by fend25** [comment]
@dev-rke the main idea was to escape the classes. 
they are pretty nice, for a first sight, but actually it will cause lot's of `this` and other questionable things like react's `this.tick.bind(this)` instead of simple `tick()` or `scope.tick()`. 
JS class system is just sugar on usual prototypes, so lot's of `bind`, `apply` and so on are still here)

**Comment by dev-rke** [comment]
Yeah, you're right, this is one reason why i love CoffeeScript.

But the question is how i can simply modify complex components, when i need to customize them?

If you would provide an accordion as component, how can i add an icon in the headline to toggle between "+" (closed accordion element) and "-" (open accordion element).

**Comment by lega911** [comment]
> If you would provide an accordion as component, how can i add an icon

You could change the template unless accordion supports icons, something like this:

``` js
alight.createComponent('myaccordion', function(scope, element, env) {

  var result = callCoponent('accordion');

  result.template = "...icons" + result.template

  return result;
});
```

**Comment by dev-rke** [comment]
When will this be available?
I have some ideas for components (e.g. a endless scrolling list, richtext editor, markdown converter, video player)

**Comment by lega911** [comment]
I can take it in package "ext" right now,
you can play with http://plnkr.co/edit/1QLX6xXnkVNkaVeDdpUJ?p=preview

**Comment by lega911** [comment]
http://jsfiddle.net/lega911/vyoq12hj/
