### ISSUE TITLE
Properties and attribures of elements

### ISSUE THREAD

**Issue by lega911** [lega911/angular-light#143]
We have just optimize events: al-mousemove, al-focus -> al-on:mousemove

What about attributes?, we have different directives to change attributes, like: al-disable, al-readonly...
we can optimize them too, someting like in Angular2

``` html
<button type="submit" [disabled]="!f.form.valid">Submit</button>
<button type="submit" [readonly]="!f.form.valid">Submit</button>
<button type="submit" [value]="!f.form.valid">Submit</button>
```

``` html
<button type="submit" :disabled="!f.form.valid">Submit</button>
<button type="submit" :readonly="!f.form.valid">Submit</button>
<button type="submit" :value="!f.form.valid">Submit</button>
```

``` html
<a al-bind:href.literal="/a/b/c"></a>
<a :href.literal="/a/b/c"></a>

<img src="/image.png" />
<img :src="imageLink" />
<img :src.tpl="/images/{{imageLink}}" />
```

**Comment by lega911** [comment]
props:
- checked / :checked
- readOnly / :readonly
- innerHTML / :html
- innerText / textContent / :text
- value / :value
- selected
- muted
- disabled

adv-props:
- className, classList / :class.active="condition"
- style[key] / :style.width = ""

attrs:
- src / :src="" / :src.tpl=""
- class /

**Comment by dev-rke** [comment]
Syntax proposal, put anything into directives (it might be easier to handle, as there is already an directive detection algorithm for DOM elements):

``` html
<button type="submit" al-attr:disabled="!f.form.valid">Submit</button>
<button type="submit" al-attr:readonly="!f.form.valid">Submit</button>
<button type="submit" al-attr:value="!f.form.valid">Submit</button>
```

**Comment by lega911** [comment]
> put anything into directives

Sure, I look for short alias
A2 and vue have "canonical" versions for this, bind-readonly="" / v-bind:readonly
so it should be al-bind:readonly

**Comment by dev-rke** [comment]
Maybe an additional directive for properties (e.g. checked state of checkboxes) would be great, too:

``` html
<input type="check" al-prop:checked="!f.form.agreement" />
```

This approach would reduce several directives, as it imitates jQuery style to the DOM.

**Comment by dev-rke** [comment]
> Sure, I look for short alias

So you define a directive and you bind an short alias (e.g. `:disabled="!f.form.valid"`) to the directive?
Sounds good for me. :-)

**Comment by lega911** [comment]
> Maybe an additional directive for properties

I want to combine attr and prop in one directive, because (I think) there are few prop, any other I can use as attr.

**Comment by lega911** [comment]
> So you define a directive and you bind an short alias (e.g. :disabled="!f.form.valid") to the directive?

yes

**Comment by dev-rke** [comment]
> I want to combine attr and prop in one directive, because (I think) there are few prop, any other I can use as attr.

Agree, but you need to handle them in the framework. And you need to update them, when new properties will be standardized. Providing different directives might be easier (and also easier for developers).
Maybe you should make these properties (like disabled, checked etc) public accessible (as public directive property), so developers can add new properties without updating the alight library.

**Comment by lega911** [comment]
> And you need to update them, when new properties will be standardized.

or when someone makes an issue

> Providing different directives might be easier

We have already have them, al-value, al-disable, al-readonly
But I don't have a directive which handles custom attributes, al-bind:title, al-bind:foo...

Also, al-bind is one-way binding, when al-value and al-checked is two-way binding

**Comment by dev-rke** [comment]
> Also, al-bind is one-way binding, when al-value and al-checked is two-way binding

I looked into the code and i think now i understand. Two-way binding needs a custom implementation, when the user e.g. types into a input field and you need to watch for the change event, right?
So we are not able to "remove" the existing attribute directives to replace them with a single one, right?
I would prefer `al-attr`, because `al-bind` is too generic name for attributes. Or will `al-bind` handle other things, too?

**Comment by lega911** [comment]
> you need to watch for the change event, right?

yes

> So we are not able to "remove" the existing attribute directives to replace them with a single one, right?

we can remove some, e.g. al-readonly, al-disable, al-src

**Comment by lega911** [comment]
> Or will al-bind handle other things, too?

I don't think so.
al-attr probably better, why A2 and vuejs use name "bind" for this (instead of attr)?

**Comment by dev-rke** [comment]
> why A2 and vuejs use name "bind" for this (instead of attr)?

After looking into the docs:
http://vuejs.org/api/#v-bind
and the code:
https://github.com/vuejs/vue/blob/dev/src/directives/public/bind.js
https://github.com/vuejs/vue/blob/master/src/directives/internal/prop.js

Still unclear.
Maybe they want to handle more then attributes in future?

**Comment by lega911** [comment]
vue.js had v-attr, but it was changed to v-bind

**Comment by dev-rke** [comment]
If you compare the old code short after it was renamed due to syntax update
https://github.com/vuejs/vue/blob/c06b4c491f33edc35e0e8a2159e4c432bdb2b78c/src/directives/public/bind.js
to the current code:
https://github.com/vuejs/vue/blob/dev/src/directives/public/bind.js
There are much changes.
Before they handled only attributes, no properties.
Now they handle attributes, properties and objects or models or some kind of data structure i do not understand.

The good thing is we now know which properties we need to handle in our implementation: `value|checked|selected|muted`

But i think they forgot the `disabled` property....

Edit: i hate github's markdown syntax...-.-

**Comment by lega911** [comment]
> But i think they forgot the disabled property....

"disabled" - is a attribute

**Comment by lega911** [comment]
what about innerHTML / innerText ? avoid them?

**Comment by dev-rke** [comment]
> "disabled" - is a attribute

Hm. 
From jQuery docs:
`The .prop() method should be used to set disabled and checked instead of the .attr() method.`

> what about innerHTML / innerText ? avoid them?

Ignore them. We already have al-html for this.
Maybe al-text would be useful, but i think this could also be done using al-html.
And: they are props, no attrs. ;-)

**Comment by lega911** [comment]
> The .prop() method should be used to set disabled and checked instead of the .attr() method.

you're right, but it works as attr as well.
I moved it to prop-section.

what about style and class? we can bind them to al-class/al-style directives.

**Comment by lega911** [comment]
a prototype is ready, example: http://jsfiddle.net/lega911/yh2o8kp7/

using:

```
al-attr:attr-name="expression/value"
:attr-name="expression/value"
```

also you can turn on modifier "tpl", if you want pass {{template}}

```
al-attr:attr-name.tpl="{{expression}}"
:attr-name.tpl="{{expression}}"
```

**Comment by lega911** [comment]
for twoway: al-value, al-checked, we can make aliases :value.twoway, :checked.twoway

**Comment by dev-rke** [comment]
> you're right, but it works as attr as well.

As i remember correctly, when only changing the attribute it would not be send correctly in a submit form.
You need to change the property or it won't work.

In your example the data binding does not work for this when checking/unchecking the last checkbox: `:checked = <input type="checkbox" :checked="box" />`

The tpl modifier is great!

I'd recommend to implement twoway sync by default for attributes which can handle two way sync.
I would typically expect twoway sync automatically for attributes which can be watched for events, i think many users would expect the same.

**Comment by lega911** [comment]
> In your example the data binding does not work for this when checking/unchecking the last checkbox:

It's oneway, from scope to element, so it does nothing when you check/uncheck it.

> I would typically expect twoway sync automatically for attributes which can be watched for events, i think many users would expect the same.

I'm not sure, need discuss it.
A2 has [checked]="name" for oneway, and ([checked]) for twoway.
vuejs has v-model for two way, v-bind is oneway.
aureliaio has `value.bind="name"` it depends on element, also it has `value.one-way, value-two-way, value.one-time`

**Comment by dev-rke** [comment]
When does it make sense in a project to have an oneway binding for the value attribute?
I see none. The only thing i could think of is that you have on one side an input field where the data is read from (this is also one way, but the other way round) but the field never gets updated when the scope variable changes from outside.
So when i process the model data, i might prefix it or replace something of it. But the input box should never get updated when i modify the value. Typically i would implement a change event handler and process the data before putting it into the scope field.

When we would use current one way binding implementation, there is no case where the user sees the updated value in a input box, but when he changes it, the scope variable should not change. It would not make any sense to update a text field without reading input from the user. If the user should not modify the content, the content should not be displayed in an input field.

So please correct me if i am wrong, but i don't see any use case.

**Comment by lega911** [comment]
> When does it make sense in a project to have an oneway binding for the value attribute?

Maybe some jquery plugin uses "value" for self, so you could use `:value` for this

> this is also one way, but the other way round

We have a few ways:
1) from scope to element:  `:checked="value"`
2) from element to scope: `@checked="value=$event.target.value`
3) two way (1+2): `:checked="value" @checked="value=$event.target.value`
4) two way by directive: `al-checked="value"`

So, you propose to break 1 and we will not have a way to do this.
Also you will have to remember which element+attr works as inverted way or not.

**Comment by lega911** [comment]
> this is also one way, but the other way round

I have an idea, inverted binding (from element to scope) not only for input/value, for everything, e.g. (al-bind)

``` html
<input al-bind:value="model" />
<div al-bind:title="model" />
```

so `al-bind:title="model"` changes scope.model when attribute "title" is changed (by jQuery or whatever). It can give you chance to communicate to jQuery plugins without writing directives.

It seems we can do this for IE8+ or earlier:
MutationObserver: IE11+, Chrome 18+, Firefox 14+
For some old browsers we can use DOMAttrModified or patch Element.setAttribute method.

**Comment by lega911** [comment]
> when attribute "title" is changed

on the other side it is an event, probably it should be in `al-on`

**Comment by dev-rke** [comment]
To bind from element to scope would require watching for the correct events, so you need to define a list of attributes and events to know which events you need to handle.

**Comment by lega911** [comment]
a note for thinking

``` html
:html="model"
:html.id=" 'templateId' "
:html.id.literal="templateId" // template id without 'quotes'
:html.url="model"
:html.url.tpl="/templates/{{templateId}}"
```

**Comment by lega911** [comment]
al-include, al-html, al-html-by-id are all about one thing - to inject html.
So I think al-attr:html (:html) could cover all cases and more. e.g. al-html-by-id can't load a template from a server, al-include can't make inner variable.

**Comment by lega911** [comment]
> To bind from element to scope would require watching for the correct events, so you need to define a list of attributes and events to know which events you need to handle.

Yes, and a developer should keep the list in his mind.
I don't want to mix different directions in one directive. We can make a separated directive or use a modificator for the inverted direction.

**Comment by dev-rke** [comment]
> So I think al-attr:html (:html) could cover all cases

Basically, yes, this could be done. 
Splitting into separate directives allows to remove these features from a custom build.

**Comment by lega911** [comment]
> Splitting into separate directives allows to remove these features from a custom build.

I will think about ability to separate it to :html, :html.id and :html.url (different files)

**Comment by dev-rke** [comment]
> I will think about ability to separate it to :html, :html.id and :html.url (different files)

This style implies .id and .url are modifiers.
By the way: we should focus on properties and attributes of elements in this issue. :-)

**Comment by lega911** [comment]
`:html` is exception, it will be al-html

**Comment by dev-rke** [comment]
When using models or accessing the html content i prefer the term al-bind.
al-attr implies only using attributes.

**Comment by lega911** [comment]
>  the term al-bind.

we alreay have al-html, I moved it to https://github.com/lega911/angular-light/issues/144

**Comment by lega911** [comment]
> To bind from element to scope would require watching for the correct events, so you need to define a list of attributes and events to know which events you need to handle.

What if we add arguments for events to simplify the event directive:

```
al-on:input="value=$value"
```

$value is taken from element.value / .checked ... depends on element
then we don't need to invert al-attr
https://github.com/lega911/angular-light/issues/145

**Comment by dev-rke** [comment]
I think this is not good.
A better way would be to focus on event binding (al-on), attribute binding (al-attr) and user input binding (al-bind or better al-input, only for two-way-binding).
Then developers understand how things work.
When putting everything into less directives, it would be hard to understand how to do it the best way.

Using al-input would be the best choice, because then you can define event watchers by the element type (e.g. input element or checkbox element).

**Comment by lega911** [comment]
> attribute binding (al-attr)
> putting everything into less directives, it would be hard to understand
> this is also one way, but the other way round

do you agree we don't need inverted binding here?

> Using al-input would be the best choice

what about textarea and select?

**Comment by dev-rke** [comment]
> do you agree we don't need inverted binding here?

We need the following binding:
element -> scopeVar
scopeVar -> element

al-attr implements scopeVar->element
al-on implements element->scopeVar
al-input implements scopeVar->element AND element->scopeVar

But al-input does not need an attribute, because there is exact one element property which changes, when the user modifies the content (e.g. checking a checkbox or changing a textarea content), so an developer does not need to give an attribute as parameter.

> what about textarea and select?

``` javascript
document.getElementById("myTextarea").value
```

and 

``` javascript
document.getElementById("mySelectBox").selectedIndex;
```

This example is already good, it only needs to be renamed to al-input:
https://jsfiddle.net/lega911/ej80e9r4/

And the al-input would work like:

``` coffeescript
alight.d.al.input = (scope, exp, element, env) ->
  if element.tagName is 'TEXTAREA'
    # execute the code here which al-value currently uses
  if element.tagName is 'INPUT' and element.attribute['type'] is 'radio'
    # execute the code here which al-radio currently uses
  else if element.tagName is 'INPUT' and element.attribute['type'] is 'checkbox'
    # execute the code here which al-check currently uses
  else
    # execute the code here which al-value currently uses for type 'text,url,password,email, etc.'
```

The exception we need to talk about would be type submit and button.

**Comment by lega911** [comment]
Alight has al-value, al-checked, al-radio, al-select, al-focused for two-way.
Do you propose combine them to one directive?

al-focused doesn't depend on an attribute, there are events only.
al-select is a difficult directive, it depends on a child ones "al-option", but you can use al-value for simple cases.

``` html
angular 1<input ng-model="todo.text" />
angular 2<input [(ngModel)]="todo.text" />
vuejs <input v-model="message" />
aurelia.io <input type="number" value.bind="model" />
```

Other frameworks have combined directives. So probably it right way. What about al-model (instead of al-input)?

> But al-input does not need an attribute, because there is exact one element property which changes

not always, type="date" has value, valueAsNumber, valueAsDate (and last 2 are more helpful then value)

> The exception we need to talk about would be type submit and button.

submit and button are usually used as events, and value of them are not very helpful. So we can avoid them.

**Comment by lega911** [comment]
we can control style via al-attr, because style attributes can't be in camelCase:

``` html
al-attr:style.width="width"
:style.width="width"

al-attr:style.backround-color=" active?'red':'green' "
:style.backround-color=" active?'red':'green' "
```

**Comment by lega911** [comment]
done, http://jsfiddle.net/lega911/vxhdcj3f/

``` html
    :style.background-color="active?'red':'green'"
    :style.border-color="color"
```

Also, I added property :hidden, so we don't need al-show/al-hide anymore, A2 has deprecated ngShow/ngHide too.

**Comment by lega911** [comment]
I've moved a question about al-input: https://github.com/lega911/angular-light/issues/149
