### ISSUE TITLE
al-html

### ISSUE THREAD

**Issue by lega911** [lega911/angular-light#144]
```
:html="model"
:html.id=" 'templateId' "
:html.id.literal="templateId" // template id without 'quotes'
:html.url="model"
:html.url.tpl="/templates/{{templateId}}"
```

```
al-html="model"
al-html:id=" 'templateId' "
al-html:id.literal="templateId" // template id without 'quotes'
al-html:url="model"
al-html:url.tpl="/templates/{{templateId}}"
```

**Comment by lega911** [comment]
done, but it can have a conflict with innerVariable

`al-html:id="name:innerVariable"`
it's ok
`al-html:id.tpl="doc-{{name}}-template:innerVariable"`
here I don't know if there is name of variable or it is a part of the template

2 solutions:
1) add modifier ".scope"
2) move inner variable to separated attribute: pass-name="innerVariable" / watch-name / watch-variable

**Comment by lega911** [comment]
http://jsfiddle.net/lega911/n67w47k8/

**Comment by lega911** [comment]
> al-html:id.tpl.scope="doc-{{name}}-template:outerVariable"

Where should we take innerName for this case?

**Comment by dev-rke** [comment]
I don't understand what this is.

**Comment by lega911** [comment]
> I don't understand what this is.

In this example http://jsfiddle.net/lega911/k0o33rkk/
`al-html-by-id="'newsitem':active"`, it binds a value from scope.active to newsitem, innerName = newsitem

What innerName should be when a template is loaded from a server `al-html:id.tpl.scope="doc-{{name}}-template:outerVariable"`, we have no name"newsitem here.

**Comment by dev-rke** [comment]
Ok, i think i understand the problem now.
But i still think this is complicated.

**Comment by lega911** [comment]
Probably we need easier api:

``` html
al-html:scope="htmlTemplate:outer -> inner"
al-html:scope="htmlTemplate:inner = outer"
al-html:scope="htmlTemplate" scope="outer -> inner"
al-html:scope="htmlTemplate" scope="inner=outer"
al-html:bind="htmlTemplate" bind="inner=outer"
al-html:scope="htmlTemplate" inner="inner" outer="outer"
...
```

anyway it is helpful to have an able to load template from server or from variable.

also I divided al-html to 4 files

**Comment by lega911** [comment]
I think it is better if a template decides what name of inner variable, it avoids an extra dependency.
We can make a tag for this in first line of template:

``` html
<script type="text/html">
<!-- name = newsitem -->
...html...
</script>
```

This approach gives us an able to define extra information:

``` html
<!-- watchMode: array -->
<!-- controller: myController -->
...
```

**Comment by lega911** [comment]
What about inline templates?

``` html

<div al-html.inline="outerName">
  <!-- name = newsitem -->
  <!-- template = inlineNews -->
  <h1>{{newsitem.headline}}</h1>
  <ul>
    <li al-repeat="it in newsitem.children">
      <div al-html:inline="inlineNews:it"></div>
    </li>
  </ul>
</div>
```

**Comment by lega911** [comment]
@dev-rke I've made modifier inline ( 5 lines of code https://github.com/lega911/angular-light/blob/master/src/html/inline.coffee )
http://jsfiddle.net/lega911/qbw5uhw3/

It takes a html of the element and saves into a variable, after that you can reuse the template within the scope.
It seems what you wanted from "template".

In previous examples we use script-template to inject it only once, so you don't need script-template anymore, you can place your template just in place where you will use it.
It's good for recursion.

**Comment by dev-rke** [comment]
> It seems what you wanted from "template".

Yes. I think we did some recursion in our discussion. :D 

> It's good for recursion.

Yes.

I like the approach.

Could you please make some docs for al-html?

**Comment by lega911** [comment]
http://angular-light.readthedocs.org/en/latest/directive/html.html

**Comment by dev-rke** [comment]
Thank you. :-)

I think this is inconsistend syntax:
`:html.id` vs. `al-html:id`

I'd recommend using 
`:html:id` vs. `al-html:id`

It is more consistent.

**Comment by lega911** [comment]
> I'd recommend using 
> :html:id vs. al-html:id

what if I make ":" and "." ([:.]) for this?

```
:html:id.tpl
:value:tpl
and
:html.id.tpl
:value.tpl
```

then I will not need to remember which symbol I should use...

Also it can be done for all directives: al-value:arg, al-value.arg ...

**Comment by fend25** [comment]
@lega911 Yes. Both thumbs up for dot-only syntax inside directives and attrs.

**Comment by lega911** [comment]
@fend25 proposes to use dot "." instead of ":", so there will no ":" (except first letter for attributes), so I will not need to remember which symbol I should use. It will be dot always.

examples:

```
al-on.keydown.left=""
@keydown.left=""

al-attr.value.tpl=""
:value.tpl=""

al-html.url.tpl=""
:html.url.tpl=""
```

`al-html.url.tpl.literal=""` is better than `al-html:url:tpl:literal=""`
@dev-rke, do you agree?

**Comment by dev-rke** [comment]
> do you agree?

I think this also would be better than using a colon, because a colon indicates XML namespaces. :-)
So we wouldn't have conflicts when someone needs to use XML namespaces for attributes.
Finally, i agree. :-)
