### ISSUE TITLE
arguments for events

### ISSUE THREAD

**Issue by lega911** [lega911/angular-light#145]
`$event, $element`

``` html
al-on:input="value=$element.value"
al-on:keydown="key=$event.keyCode"
```

$value and other?

**Comment by dev-rke** [comment]
You only should provide $event, because one should get the element using $event.target.

**Comment by lega911** [comment]
>  one should get the element using $event.target.

You still can use $event and $event.target, why having $element and $value is bad, they don't prevent you.

Also $element not always equals $event.target, because event can come from a child element ("bubble")

**Comment by dev-rke** [comment]
> Also $element not always equals $event.target, because event can come from a child element ("bubble")

Ok, now i accept it. ;-)
