### ISSUE TITLE
Pagination Example

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#150]
I had several times the case to implement a pagination.
The already existing "slice" filter works, but is a bit difficult to implement, when there are very much conditions to respect. I wrote a simple viewhelper, which can be extended to adress this kind of case:
https://jsfiddle.net/44kkL90t/

As alternative here a "simple" implementation using the "slice" filter (i recommend to put this on angularlight.org examples section):
https://jsfiddle.net/8y2cfseq/

**Comment by lega911** [comment]
> https://jsfiddle.net/8y2cfseq/

1) Your example works correctly only when length of list = 100 :)

> al-repeat="it in pages"

2) You don't have to make list "pages", al-repeat can iterate by number

``` html
<div al-repeat="n in 10">
  {{n}}:
  {{$index}},   {{$frist}},   {{$last}}
</div>
```

3) You don't need "scope.$scan()" when a binding process works / first time call, beacuse the binding process do it on finish.

So your example can look something like this: https://jsfiddle.net/lega911/8LtjdvLa/

**Comment by lega911** [comment]
I think about moving a source of the site to github, so you will be able to append examples any time.

**Comment by dev-rke** [comment]
> 1) Your example works correctly only when length of list = 100 :)

Ok.

> 2) You don't have to make list "pages", al-repeat can iterate by number

Interesting, didn't know that, i need to put a watcher on the docs. :D

> 3) You don't need "scope.$scan()"

You're right, this was dead code.

> So your example can look something like this

There is a bug when clicking the last page vs. clicking the button "last page": they produce different results.

I applied your improvements to my approach:
https://jsfiddle.net/3zqyyjus/

> I think about moving a source of the site to github, so you will be able to append examples any time.

That would be great!

**Comment by lega911** [comment]
I added it to http://angularlight.org/doc/examples.html
