### ISSUE TITLE
async filters

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#153]
I have the following code, which works:

``` coffeescript
alight.filters.validateGroup = class X
    watchMode: 'array'
    onChange: (oldGroups = []) =>
        setTimeout =>
            @setValue (group for group in oldGroups when group.counter > 0)
```

I'd like to know why i definitively need to use setTimeout.
When i remove the setTimeout function, it won't work anymore.
I understand that the filter is called "async", but i do not understand, why i need to handle this manually.
Also i thought the filter would be applied by watching the result of al-repeat, and if it changes, the onChange method is executed.
Can you explain, why the async part is necessary? It would be great to put this also to the docs.

**Comment by lega911** [comment]
try to use a not-fat arrow (->) for class, => can give you wrong "this"

``` coffeescript
alight.filters.validateGroup = class X
    watchMode: 'array'
    onChange: (oldGroups = []) ->
        @setValue (group for group in oldGroups when group.counter > 0)
        return
```

**Comment by dev-rke** [comment]
You inject the setValue method as prototype into my class, am i right?
Then the scope should be correct with `=>`.
Your approach with `->` does not work, i need the setTimeout.

Some more information, about what i am doing:
I render groups into multiple select elements:

``` html
<option data-al-repeat="group in filteredGroups | validateGroup" data-al-option="group">
  {{group.title}} ({{group.counter}})
</option>
```

`filteredGroups` gets updated by a filtering method, when other input elements are used.
I do not use the filter "filter", because it is too limited for my use cases.
So as i understand the process works as follows:
1. filteredGroups gets modified
2. The watcher of al-repeat triggers change event of the value
3. The watcher pipes the changed result to the validateGroup filter
4. The validateGroup filter sets the new result, which will be rendered by al-repeat

Is my understanding correct?
Do you have some ideas how i can better debug this?

**Comment by dev-rke** [comment]
Ok, i found out, that my validateGroup filter runs, after this the filteredGroups scope variable gets updated.
When i execute the filtering manually, the filter is initiated correctly, and then it works.
Crazy stuff....

**Comment by dev-rke** [comment]
Omg, got the source of the issue.
My code did not "initialize" the filtering process on startup, i had to do a major change (complete new layout, other filtering technique) and before the initial filtering was executed by $watch methods.

A question to the $watch method of a scope: is it possible to exclude properties by name?
I need to track an array of objects, which have hierarchical relations (children and parent property) and therefore it ends in too much recursion.
Before i initalized the tracking of these variables by mapping a $watch method for each array item.
But this is not very performant, because the watcher automatically fires at initialization and the filtering runs five times on startup. I think this could be done better.
How do i use the function instead of a expression as $watch paramter, as mentioned here:
http://angular-light.readthedocs.org/en/latest/change_detector.html
?

**Comment by dev-rke** [comment]
Another idea: is it currently possible to watch only a defined depth?
Currently the option deep:true watches all levels.
I only need to watch the first two levels.

**Comment by dev-rke** [comment]
I made a simple example:
http://jsfiddle.net/gqtguovs/

I want the watcher to handle my text when i press the button "change title", not when i press "add watcher". The watcher callback should be only executed when the value was changed.
The other approach is to force the watcher only to watch to depth levels.
The third approach is, that i do not have further objects which have children or parent elements.

What do you think would be best?

**Comment by lega911** [comment]
wow, so much, do you still have a problem with your filter?

> I want the watcher to handle my text when i press the button "change title", not when i press "add watcher". 

the best solution is using a handler (function) instead of expression:
`al-click="title = 'test after'"`
change to
`al-click="handler()"`

But you can do something like this: http://jsfiddle.net/lega911/7vfpfdet/

**Comment by lega911** [comment]
or http://jsfiddle.net/lega911/p8qeu6q2/
or deferred: http://jsfiddle.net/lega911/g5fmuboo/

**Comment by lega911** [comment]
it is based on a text directive: https://github.com/lega911/angular-light/blob/master/src/text/textWatch.coffee

**Comment by lega911** [comment]
Maybe you want this? http://jsfiddle.net/lega911/o8erofa1/

**Comment by lega911** [comment]
http://jsfiddle.net/lega911/u3y3fy5q/

Am I right understand your issue?

**Comment by dev-rke** [comment]
>  http://jsfiddle.net/lega911/u3y3fy5q/
> Am I right understand your issue?

This last example exactly matches my requirements (i also thought about this), but i have to implement this for 8 different watch handler (propably more in future). This is a bit "ugly" to have so much conditions doing the same.
Yes, i could abstract this into a method, but i think its still ugly.

The problem is, that i use different directives and can't use handler scope methods in all of them (e.g. al-select does not allow using a method as far as i understood).
So i try to use scope variables and change them, because this can be done in all cases.
I have links, select boxes, text input and propably soon some checkboxes/radio buttons.
If i modify the code to avoid the recursion due to hierarchy in the variable, i need minimum double amount of code for the same (estimated).

I handle around 500 products in the browser and when executing the filter 4 times initially there are 2000 iterations (it's still very very fast, but when i have 3000 products there will be 12000 iterations and so on...)
The rest of the code is optimized for performance, this is the only bottleneck i stumbled over. :D

If you have any further idea, please let me know. :-)

**Comment by lega911** [comment]
> Another idea: is it currently possible to watch only a defined depth?

you can watch a function: http://jsfiddle.net/lega911/q7mh48wb/

**Comment by lega911** [comment]
> when i have 3000 products there will be 12000 iterations and so on...

The fastest way is making result array by hand.
Angular Light can serve 10M+ watchers per second, and usually a bottleneck is DOM and rendering, so if you have a lot of DOM it is first reason of a slow application.

**Comment by dev-rke** [comment]
> Angular Light can serve 10M+ watchers per second

I know that JavaScript can be fast and also handle huge of memory.

> and usually a bottleneck is DOM and rendering, so if you have a lot of DOM it is first reason of a slow application.

No. Our Bottleneck are older mobile devices, which have less memory and slow processing power.
Currently my DOM is small, the page loads fast and is fast rendered. 
I just want to avoid unnecessary iterations due to framework handling. That's all. :-)

Would it be possible to define instead of the option `deep: true` the depth of levels the watcher should look for, e.g. `deep: 2` to watch exact 2 levels?
The advantage is, that this also would increase performance for normal watching structures.

Thank you for supporting me. :-)

**Comment by lega911** [comment]
> look for, e.g. deep: 2 to watch exact 2 levels?

yes, why not
but anyway, custom-watch (watch function) can give you better performance

**Comment by lega911** [comment]
> e.g. deep: 2 to watch exact 2 levels?

done, http://jsfiddle.net/lega911/o1qvt257/

**Comment by dev-rke** [comment]
This is really great!
Works as expected. :-)
