### ISSUE TITLE
rendering html using text directives

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#154]
Is it possible to render html from a RTE using text directives?
I only know al-html that could do this, but it would require an additional wrapping html tag.

**Comment by lega911** [comment]
text-directives work with text only, e.g. scope.$watchText('{{#dir}}', callback); you don't need DOM as result in callback

> Is it possible to render html from a RTE using text directives?

look at this example: http://jsfiddle.net/lega911/n67w47k8/

you can use RTE converter instead of markdown

**Comment by dev-rke** [comment]
> you can use RTE converter instead of markdown

I do not need to convert anything, i need to place a html block as text.
Can i use an html comment to place a directive? As i remember correctly this is possible for al-repeat. Is it possible for al-html too?

**Comment by lega911** [comment]
> a html block as text

ok, I get it,
yes, you can use text directives for this, I'll make an example later

**Comment by lega911** [comment]
No, I don't understand what you want, it would be nice to see example
Here example of "comment"-directive: http://jsfiddle.net/lega911/hby962Lr/

**Comment by dev-rke** [comment]
I need to place some html as text without masking:

``` javascript
scope.value="Hello<br />World";
```

``` html
{{value}}
```

Expected Output:

```
Hello
World
```

Current Output:

```
Hello<br />World
```

At the moment i use a wrapping paragraph with al-html directive, this works and is ok for me.
Another solution would be this, if it would work: http://jsfiddle.net/js3zgd1c/

**Comment by lega911** [comment]
> {{value}}

you can make " {{{value}}}" or #html:value or... using hooks.binding, but it's not good way: http://jsfiddle.net/lega911/nqj3mo3o/

I will make al-html for comments

**Comment by lega911** [comment]
You can't use "text" for this (text-directives), because you need DOM as result, and it is impossible to include DOM into an attribute of element (title="{{value}}")

**Comment by lega911** [comment]
done http://jsfiddle.net/lega911/d62ap18L/

**Comment by lega911** [comment]
it seems you need it without a container... right?

**Comment by lega911** [comment]
done http://jsfiddle.net/lega911/z2v6zosg/

**Comment by lega911** [comment]
now text-directives don't require watchers, it's mean, for example, you can make translation without a load for $scan, e.g. {{^ text for translate}} http://jsfiddle.net/lega911/fqnhv94q/

**Comment by dev-rke** [comment]
Oh my god :-)
Do I need to wait for a new bower release or is this already possible with 0.12.16?
As i wrote before it is OK for me using paragraph container. I just want to know if it is possible without a container.

**Comment by lega911** [comment]
I updated bower and npm. I just don't want to make new release (version) on every minor changes.

**Comment by lega911** [comment]
I've made one more optimization :)
this example has only one watcher! http://jsfiddle.net/lega911/d64hx7Lj/

1) events: `@click, @input` don't make watchers
2) text directives `{{^ Some header}}` don't make watchers
3) bindings that are placed close to each other are united `{{one}} {{one.toUpperCase()}}` they make only one watcher

**Comment by dev-rke** [comment]
Ok, but i still do not understand why you provided this example. 
It does not handle my problem. ;-)
But it is great to see that translations are simple to implement. :-)

The best solution for my initial problem is this example you provided: https://jsfiddle.net/lega911/d62ap18L/
Thank you very much supporting me. :-)

**Comment by lega911** [comment]
> i still do not understand why you provided this example. 

Don't pay attention, I wanted to share about this feature with someone who understand text-directives... :)
