### ISSUE TITLE
Changing scope variable inside of a watcher

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#159]
I wrote a filtering class:

``` coffeescript
class myClass
  filter: {
    sword: ""
    productGroup: null
    productSize: null
  }

  constructor: ->
    @$watch "filter", @executeFilter, deep: 3

  _resetFilters(newFilter, oldFilter): =>
    for key,filter of oldFilter when key isnt "sword"
      if newFilter[key]? and newFilter[key] isnt oldFilter[key]
        @filter.sword = ""

  _processFilters: () =>
   # do something to filter data

  executeFilter(newFilter, oldFilter): =>
    @_resetFilters(newFilter, oldFilter)
    @_processFilters()
```

Now i need to reset the filter variable sword when another filter is set.
When i filter using the sword field other filters should not be affected.
The sword variable is a text input field, the other filters are select elements.

My problem is the `@filter.sword = ""` assignment.
When i want to reset the filter, the text input element does not update it's text.
Do you have an idea, what i could do to reset a specific filter item?
I already tried to fire an `@$scan()`, also deferred using setTimeout.
Is it possible to change a watched scope variables inside of a watcher?
If not, might it be possible to temporary "exclude" a scope variable from watching?
I remember you have a concept in a directive, but i do not find it in the source.

**Comment by lega911** [comment]
I don't see a problems: http://jsfiddle.net/lega911/deg4ywo6/

**Comment by dev-rke** [comment]
Hm, i am wondering.
I will test it again later.
My processfilters method takes around 50-250ms. Could this be the Problem?

**Comment by lega911** [comment]
> 50-250ms

too much, can you make an example? there is can be infinity recursion.
alight.debug.scan = 1; or alight.debug.scan = 2; can display what is changed (be careful, it can give you a huge log)

**Comment by dev-rke** [comment]
`$scan: loops: (2), last-loop changes: 0, watches: 157 / 58ms`
I assume this is the time consuming part. ;-)
I think i've got no recursion, the time consumption is caused by filtering 500 records.

**Comment by dev-rke** [comment]
It works partially in my local environment.
When i enter "test" into the sword filter (causes a scan) and after this changing the first select element (causes 2 scans, one for select and the other for `@filter.sword = ""`) it works.
When doing this again, it sometimes works, sometimes it does not.
I assume, that the object references in newFilter vs. oldFilter are different, because my `productGroup` variable is an object reference:
http://jsfiddle.net/aq7vqbhz/1/

And when these are different object references, the line `newFilter[key] === oldFilter[key]` would not work, and this might cause the problem.
I can reproduce the behaviour in Firefox after three or four tries.

Do you have an idea what other options i have?
The simplest option would be appending an event to the select elements to reset the sword filter.
But this is not generic, i'd like to have a generic approach to re-use the code for other projects.

**Comment by lega911** [comment]
I've found 2 problems:
1) your _resetFilters assigns @filter.sword = "" on every scan loop.
2) al-value="filter.sword" is not updated because, when $scan checks "filter.sword" it is always = "", (always the same -> no changes -> no update).

I fixed your filter: http://jsfiddle.net/lega911/jq82uf85/

**Comment by lega911** [comment]
> "filter.sword" it is always = ""

if you append "{{filter.sword}}" you can see it. your filter hits "sword" first.
For this case al-value should be first, I have an idea how to fix it.

It's not often case, -  if you change a value that just was changed, and your handler goes first.

**Comment by lega911** [comment]
> It's not often case, - if you change a value that just was changed, and your handler goes first.

only if the handler assign previous value ("")

**Comment by dev-rke** [comment]
> 1) your _resetFilters assigns @filter.sword = "" on every scan loop.

I added a return statement. I forgot this in the example code.
http://jsfiddle.net/u8xw27x6/

> 2) al-value="filter.sword" is not updated because, when $scan checks "filter.sword" it is always = "", 

Ah, interesting. I need to debug further. :-)

> I have an idea how to fix it.

Do we need a fix? 
Or is it better to use another approach?
The current concept is nearly the same which AngularJS uses.
So i think it wouldn't be useful to provide domain specific features to alight, it would be better to use generic approaches.

**Comment by dev-rke** [comment]
Yippieh!
I found a solution after two and a half days, due to your hints:
http://jsfiddle.net/kgdat0ob/

The idea is to check if the sword filter hasn't changed and then to reset the sword.
If it has changed we do not reset the sword.
This is far more generic, because i can have different dynamic filters in my application.
Thank you very much. :-)

Recommendation: it would be great if the docs would contain an information about scope.$watch callback parameters, i did not knew that i get the newValue first and the oldValue second, i needed to debug this. :-)

**Comment by lega911** [comment]
> The current concept is nearly the same which AngularJS uses.

Have you tried it in Angular.js ?

> The idea is to check if the sword filter hasn't changed and then to reset the sword.

I would separate "sword" to another watcher

**Comment by dev-rke** [comment]
> Have you tried it in Angular.js ?

Nope, but i searched for my problem and several stackoverflow comments recommend to use a helper variable to "toggle" the execution of the filter in a second state.
I see that AngularJS uses nearly the same concepts as alight does. And this is good. :-)

> I would separate "sword" to another watcher

I also thought about this, but for the first approach we need to "fix" the problem, not optimize it. :-)
I definitively will think about this.

**Comment by lega911** [comment]
ok, my idea works well, (I fixed 2nd problem from above), and it deprecates another code, so alight will be a little lighter.

I'll make a release a little bit later (refactoring required)

**Comment by dev-rke** [comment]
Great! :-)

**Comment by lega911** [comment]
done

**Comment by dev-rke** [comment]
I try to understand how the Change https://github.com/lega911/angular-light/commit/27508d4aa04e86d735ee128bf09a5fdb049ef57d in the ChangeDetector works.
Before the Change there was a skipWatch property, which ignores a watch when running a scan.
After the Change we have a refresh() method.
It seems the refresh is required to update referenced objects.
So you changed from an implicit behaviour to an explicit behaviour, right?

**Comment by lega911** [comment]
> So you changed from an implicit behaviour to an explicit behaviour, right?

I don't know, maybe.

Refresh just updates (prevous) value of watcher-object,
1) so, in next $scan process, it will not have a change event
2) if there is a handler that changes this value, then we will have the change event (to update input-element, problem 2 from above)

So it looks like manual synchronization input-element and watcher-object.

**Comment by dev-rke** [comment]
> I don't know, maybe.
> Refresh just updates (prevous) value of watcher-object,

Ok. Before you need to "exclude" a watcher if it should not get updated (implicit behaviour, because by default all watchers get updated), now you need to refresh manually (explicit behaviour).

I'll give it a try. :-)
Thanks for your great support.
