### ISSUE TITLE
Limiting the number of events added to the DOM

### ISSUE THREAD

**Issue by djkunkel** [lega911/angular-light#162]
If I have an al-repeat that generates a rather large number of checkboxes (several hundred) inside a ul, each bound using the al-model directive. It seems somewhat slow initially to bind. Is there any recommended practice or example of using event bubbling to only listen to the list for events from the inputs below it to handle the model updates?

I've experimented with using a @click.noprevent handler on each checkbox that returns '$scanNoChanges' if the handler doesn't need to change anything else  and a :checked attribute to load the state back into inputs with success, but I'm wondering if there's a more preferred solution you've seen/done.  I'm assuming each one of these checkboxes has a dedicated event handler, and wondering if there's a way to limit how many of these are created.

Thank you again

**Comment by lega911** [comment]
I usually try not to make a huge components, (pagination, search box, etc).
Also I different parts (components) make as isolated components (that contain own root scope)

You can use bubbling like this: http://jsfiddle.net/lega911/m5048y41/
events have modifier "noscan".
in a pinch you can make custom directive.

**Comment by djkunkel** [comment]
OK. Example makes sense.  Thanks!  Can you explain what you mean by:

> Also I different parts (components) make as isolated components (that contain own root scope)

**Comment by lega911** [comment]
http://plnkr.co/edit/uWsrdf5vagLxhkZs9pwN?p=preview
http://plnkr.co/edit/l0O76klZhbclUW7L5YMS?p=preview

Look at these two examples, they have components with the same features, but second example has much less watchers and scan works only for one component.
This approach can increase performance up to thousand times in big application.

**Comment by djkunkel** [comment]
This is fantastic, and I want to take advantage.  When I switched it to use version .12, filter 'generator' is no longer present.  Has this been moved or replaced?  Also the only values valid for scope now are false,true, and 'root'.

I really appreciate it.

**Comment by djkunkel** [comment]
I modified the root scope one to work with 0.12
http://plnkr.co/edit/8YsGJ1?p=preview

Thank you!

**Comment by djkunkel** [comment]
Referring to your earlier example about bubbling:

> http://jsfiddle.net/lega911/m5048y41/

I note that when doing:
http://jsfiddle.net/4yyqbjs5/  with debugging on
alight still generates 1000 watches

When switching to the bind once syntax:
http://jsfiddle.net/wyuv1u97/
it no longer generates the watches, but it does do 1000 scans initally

Is there any way to get al-repeat to build the html and do a single scan afterwards?

Thanks again.

Edit: If I wait till finish binding and use al-if to add the ul to the dom, those initial 1000 scans no longer happen, here's an example with selection tracking, event bubbling, resetting of a checkbox list using this technique:
http://jsfiddle.net/vjozb04L/

**Comment by lega911** [comment]
> filter 'generator' is no longer present. Has this been moved or replaced?
> scope.boxes =[];while(scope.boxes.length<1000)scope.boxes.push(scope.boxes.length+1);

you don't need it anymore, al-repeat can iterate by number: al-repeat="i in 1000" (look first example), al-repeat="i in length"

> alight still generates 1000 watches

because of id="i{{$index}}", fixed http://jsfiddle.net/lega911/9pwrj70f/

in a pinch you can make a custom directive, make and control DOM manually, so alight will not affect on it, you will have max performance.

Also you can make "virtual build", render only a few checkboxes, but user will think about thousands, this way give you possibility to "make" millions items and more :)
example: http://jsfiddle.net/lega911/zpcq8wjo/

**Comment by djkunkel** [comment]
> you don't need it anymore, al-repeat can iterate by number: al-repeat="i in 1000" (look first example), al-repeat="i in length"

Yeah, I did that so I could prove to myself that I could add new boxes and have them appear on a rescan.

> because of id="i{{$index}}", fixed http://jsfiddle.net/lega911/9pwrj70f/

Yes, this does stop the watches, but now it does 1000 scans on initial binding. In my example, when having it disabled by al-if on load time, and then showing them, this didn't happen.

> Also you can make "virtual build", render only a few checkboxes...

This is a fantastic idea.  Thank you!
