### ISSUE TITLE
Component example, passing more than a direct property of the parent scope

### ISSUE THREAD

**Issue by djkunkel** [lega911/angular-light#164]
In you component example, it doesn't seem to work to pass in a property of a property of the scope. Is there a way to do this, or is this just a partially working example?

http://plnkr.co/edit/zTqE6ehvwnJgK567guQJ?p=preview

Here, my app has a property 'data' with a property 'title'  It works in the even handler, but using the :prop syntax it fails.

> <myinput @update="data.title=$event.value" :value="data.title"></myinput>

Thank you!

**Comment by lega911** [comment]
Hello!
It had a bug, this one works better http://plnkr.co/edit/1QLX6xXnkVNkaVeDdpUJ?p=preview

**Comment by djkunkel** [comment]
Perfect! Thank you.
