### ISSUE TITLE
Filters usage

### ISSUE THREAD

**Issue by bdandy** [lega911/angular-light#165]
Filters usage is very limited right now.

I haven't found how to use filter in my directives.
For example:
`scope.$eval('messages | filter: search')` will not filter messages.
There should be a way to use filters not only just in templates.

Also a question:
For example I use such template:

```
<div al-directive>
<div al-repeat="msg in messages | filter: search | slice: 1,20" al-otherdirective>{{msg}}</div>
</div>
```

How can I get filtered messages collection from any directive?

**Comment by lega911** [comment]
> How can I get filtered messages collection from any directive?

You can use "store to" variable

```
al-repeat="msg in messages | filter: search | slice: 1,20 store to filteredList"
```

> scope.$eval('messages | filter: search')

it was possible in old version of alight, now all filters are async, e.g. a filter can do ajax requests, and it's impossible to use it as sync.

you can use $watchText for this, example: http://jsfiddle.net/lega911/mqofahy9/

**Comment by lega911** [comment]
> store to filteredList

I've just looked, al-repeat has not supported it anymore, there is a filter storeTo that you can use for any expression, try this:

```
al-repeat="msg in messages | filter: search | slice: 1,20 | storeTo:filteredList"
```

**Comment by lega911** [comment]
example: http://jsfiddle.net/lega911/yvrk2490/

**Comment by bdandy** [comment]
thank you for answers. I think we could improve documentation, because some things really hard to understand (and source code doesn't help).

What about direct filters usage? I mean something like `alight.filters.filter(messages,scope,env)`
For example, I wish to use `filter` in my own filter.

**Comment by lega911** [comment]
documentation is here https://github.com/lega911/alight_docs pull-requests are welcome

> some things really hard to understand

ask me, I'm not good in writing docs

> What about direct filters usage?

It should be vice versa, you make a function for a filter, and the filter uses the function. So if you need direct usage, you can use the function.
Filter is a way to use your function in expressions and templates.

So usually you don't need direct filter usage. Probably I should expose a function for filter "filter"
