### ISSUE TITLE
Scans with al-repeat and static binding

### ISSUE THREAD

**Issue by djkunkel** [lega911/angular-light#166]
Is this normal?  When using static binding syntax (or one time binding) inside al-repeat scan debug shows at least one scan for each element in the repeater.  When using normal binding {{x}} this doesn't happen.  Is this a quirk of the debugger or is there something to this?

http://jsfiddle.net/keeuo1Lk/

**Comment by lega911** [comment]
> at least one scan for each element in the repeater

it's ok for usual binding (if you use directives), but here "fast binding" is used, yes it makes extra scans (at least if you use more then one bindonce), I will fix it.

**Comment by lega911** [comment]
fixed

**Comment by djkunkel** [comment]
Thank you!

On May 24, 2016 2:57 PM, Oleg Nechaev notifications@github.com wrote:

fixed
