### ISSUE TITLE
Add support for data attributes

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#17]
Hey,

i just thought about a light and small angular library and found this - i like your lib!
To be more html5 conform i would recommend to support data attributes as angular does.
e.g. <div data-al-click="doAnything()"></div>

**Comment by lega911** [comment]
Hello,
ok, but you can just rename prefix al -> data, [example](http://jsfiddle.net/lega911/jko4kLxn/), or rename directives.

**Comment by dev-rke** [comment]
Thank you that is great!

**Comment by dev-rke** [comment]
Hi,

the basic idea works well, but when using more complex structures i have some troubles using the following code:

``` coffeescript
alight.directives.data = {}
for name,dir of alight.directives.al
    alight.directives.data["al" + name[0].toUpperCase() + name.substr(1)] = dir
```

This code maps directives like

``` coffeescript
alight.directives.al.click
```

to

``` coffeescript
alight.directives.data.alClick
```

This snippet works well using valid directives like

``` html
<button data-al-click="app.click()">Click</button>
```

But when i define other data attributes like

``` html
<div data-test="test">Div with data attribute</div>
```

i get an exception: "Directive not found: data-test", because this directive is not defined.

I think it should be possible to define a custom prefix and the prefix should also be html5 valid using data attributes.

When rewriting the code to

``` coffeescript
alight.directives.dataAl = {}
for name,dir of alight.directives.al
    alight.directives.dataAl[name[0].toUpperCase() + name.substr(1)] = dir
```

nothing works anymore, data attributes are not recognized.

Do you have any idea how to parse "data-al" attributes but not "data-<anything>" attributes?
It would be great if it would be possible to define directive prefixes using camelcase to implicate a hyphen.

**Comment by lega911** [comment]
then .dataAl.value and .data.alValue will make the same attribute

**Comment by dev-rke** [comment]
Ok, thats true, i did not mention that.

I also tried it by defining
alight.directives['data-al'] = alight.directives.al
but it wont work either.

Would it be possible to extend the preprocessor to parse data attributes as prefix of html5 standard, too? So data-al-click could be handled as al-click per default.

An alternative solution would be to stop throwing a "directive not found" exception when using a not implemented directive - it wouldn't be good, because invalid attributes get also parsed and processed, but it would be a "first try".

Another solution could be to replace attributes starting with "data-al-" with "al-" before bootstrapping alight - but i assume this would reduce the page performance due to slow dom access performance - so i would like to see a javascript oriented solution.

**Comment by lega911** [comment]
I made some changes, now it should [work](http://jsfiddle.net/lega911/prspak5f/).

**Comment by dev-rke** [comment]
Wow! That was really fast!
It works very well, thank you very much! :-)
