### ISSUE TITLE
al-value for select lists

### ISSUE THREAD

**Issue by djkunkel** [lega911/angular-light#174]
Hello!  Is there any recommended way to do this in the latest version of Alight?  I'm looking to maintain maximum compatibility with the standard select list, and found this example.  I'd like to use al-select, but the Mapper makes it difficult for some other code I'm working with to select a value in the list, or simply get the basic value of the selection.

http://jsfiddle.net/lega911/2xou8atg/

Any suggestions?  I'd like to specify just simple values for the select items and have it update the model with those simple values.

**Comment by lega911** [comment]
Hello!
I updated the example on latest alight: http://jsfiddle.net/lega911/2xou8atg/ this do you need?
I don't understand the problem with Mapper, if you give me an example I will be able to fix it.
Here you can see more examples for select: http://angularlight.org/doc/examples.html#search=select

**Comment by djkunkel** [comment]
Thank you for this. 

I was looking for a way to find the actual value of the select list by just knowing the element. Since the value of an al-select list is a key for the mapper it isn't easy to figure out.  I had some code that didn't know about the model basically for debugging purposes and I wanted to find the values of the drop downs that happened to be visible.

I was also looking for a way to select the first item in the list if the current value of the select list was no longer present in the list.  My client has me creating a rather complicated UI with drop down lists whose available values change based on other selections, but he never wanted any drop down to remain without a selected value. I settled on forcing a change event after changing the dropdowns selectedIndex to 0 if nothing was selected in the $finishScan. I suppose I could have set each drop down's selected model item to the first item in the list when I changed its value, but I was considering a generic approach that would work when future drop downs were added.

Here's rather a crude example:
http://jsfiddle.net/a6c0em7q/1/

**Comment by lega911** [comment]
If you need only to get value, look at this 3 examples: http://jsfiddle.net/lega911/3qbhevzq/

instead of $('select'), you can use

``` html
<select al-init="initSelect($element)">
```

you can see it in the example above

if you need to choose the first item, do it in the scope: http://jsfiddle.net/lega911/rys8tnsh/
al-select syncs scope and element

**Comment by djkunkel** [comment]
Thank you for this, and for bearing with me.

**Comment by djkunkel** [comment]
One more thing I noticed.  If you don't set a selected value, but change the list a repeater in an al-select is watching to one that it a subset of the list it had before, it seems to visually select the first element in the list, but not update the value.

Am I just in a weird edge case and not having a selected item is abnormal and is it not supported to use a list that is a subset of another one when binding to a select?  I was hoping to use "filter" to change the list of available options, but continuing to leave the current one selected if it is in the subset.

In this example try selecting Text2 first then clicking to change the list.  Since Text2 is not present in the list, I'd expect it to be blank, but instead is shows Text1, but doesn't change the value.  

If you modify the code to clone the results from filter, it shows a blank item when doing this action.

http://jsfiddle.net/a4k0fg2a/

**Comment by lega911** [comment]
fixed
