### ISSUE TITLE
CoffeeScript integration

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#18]
As i develop most of client side applications in coffeescript, 
i would like to see some coffeescript specific examples and some new coffeescript specific features.

In plain Angular i am able to write something like:

``` coffeescript
app.controller "MyAppController",
    class SnippetizeController
        isCreateFormVisible: false
        isAboutDialogVisible: false
```

to autoinstanciate a class in my template when using 

``` html
<body data-ng-controller="MyAppController as myApp">
...
</body>
```

It would be great if the controller of alight would allow a syntax like that to support coffeescript classes per default to write good applications with small effort. :-)

**Comment by lega911** [comment]
You can make a wrapper for self, [example](http://jsfiddle.net/lega911/smfuncgr/).

**Comment by dev-rke** [comment]
Great! Thank you!
