### ISSUE TITLE
Does bo-switch only work with string values?

### ISSUE THREAD

**Issue by djkunkel** [lega911/angular-light#200]
http://jsfiddle.net/y3neb65r/

Thanks

**Comment by lega911** [comment]
yes, https://github.com/lega911/angular-light/blob/v0.7.15/alight/directives.coffee#L466
there is strong comparison (by CoffeeScript)

**Comment by lega911** [comment]
http://jsfiddle.net/ntq1jomc/

**Comment by djkunkel** [comment]
Thank you as always.
