### ISSUE TITLE
Project references?

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#21]
Hi,
are there any project references, e.g. any webpages already using your framework?
As i saw on bitbucket you are developing it since a few years and it also seems to be well tested.
I would appreciate to see some real world production environments to get an insight how different developers use it.

**Comment by erickskrauch** [comment]
I can show you my [Ely.by](http://ely.by) project. For example in [my profile](http://ely.by/erickskrauch), [skins](http://ely.by/skins).

**Comment by dev-rke** [comment]
Wow, pretty cool, especially the profile view.
I also like your cube loading animation. ;-)
As i do not understand cyrillic language, it seems to be kind of a forum or social network, am i right?

Do you have some experience with normal angular.js?
What benefits of angular-light do you see in contrast to angular.js?

I am asking because i want to discuss with my colleagues to use this project, i see some benefits, but i need some more "facts" to convince them.

I think i'll give it a try, so my next personal project will be "alightened". :-D

**Comment by erickskrauch** [comment]
I would gladly describe all the charm of Angular light before his big brother, but how did you understand I speak Russian, and I myself from Belarus, so I used Google Translate, to write this message and all in all I could not express my thoughts in English, sorry.

In short, the Angular light - it's not a framework, but simply a library that bears the same idea Angular, but does not impose it - you can implement any component itself, as you and your project need it.

Work outside the stack Angular very difficult (impossible?). Work outside the stack Angular light easier than ever - you can impose on the scope of any piece of html code.

Angular light is much easier to learn, because you have a basic controller, model and directives and further you have to develop their own services as you need it, and not like Angular guys decided.

**Comment by lega911** [comment]
Nowadays Angularjs has not the best of times, it can be difficult for beginners, version 1.x is going to die (Angular.js 2.0 is not compatible with 1.x), Angular 2.0 has no certainty (the developers have changed a main language, there is no release date, what browsers will be supported and so on), one of angularjs core team left the project, also many other frameworks have appeared.

I used Angular.js, and sometimes I had different problems - I think you know [this image](http://hsto.org/getpro/habr/comment_images/b4f/e8b/66c/b4fe8b66c2aecccf55ab897115878b51.png)

when I started using Angular Light, my speed of development accelerated.

The most important, Angular Light lets you make own architecture of application, own services, factories and so on, Angular Light is more flexible than original. Also there are number of helpful features like text-directives, inheritance of directives, namespaces, private directives and so on, which Angular.js doesn't have. Besides this Angular Light supports Object.observe.

**Comment by dev-rke** [comment]
Hi Oleg,

thank you for your explanations.
I also had the "learning curve" of ups and downs with plain AngularJS and i understand the benefits and flexibility of your framework.

I have some open questions, so i think it would be useful to label this issue as question:
- Is Angular Light compatible to zepto.js (http://zeptojs.com/)?
- Are JavaScript dom events propagated to parent dom elements?
- Can i create custom events that can be bound to a dom node? An example would be great.
- How to autostart the bootstrap correctly? In jsfiddle i have problems to get it started (i used al-app on the container div), i can only call the bootstrap method manually to get it running.
- I did not find an example for translation handling - do i have to implement it myself? I would prefer to use a text-directive, is this right?
- Is there support for ajax calls built in?

And last but not least a question to answer it would be very helpful to have a small example:
How would you generate e.g. a form dynamically? Is the dom event binding dynamic?
I would like to insert dynamic content into the dom and want to bind all al-events of the inserted content.

Thank you for your support,

Reiner

**Comment by lega911** [comment]
> Is Angular Light compatible to zepto.js (http://zeptojs.com/)?

I think, there is no problems.

> Are JavaScript dom events propagated to parent dom elements?
> Can i create custom events that can be bound to a dom node? An example would be great.

You work with native DOM, so you can do what DOM supports.

> How to autostart the bootstrap correctly? In jsfiddle i have problems to get it started (i used al-app on the container div), i can only call the bootstrap method manually to get it running.

For jsfiddle I usually set option "no wrap - in head" - it launches my code before start.
[A few ways to bind a model to the DOM](http://angularlight.org/tutorial/bindings.html)

> I did not find an example for translation handling - do i have to implement it myself? I would prefer to use a text-directive, is this right?

I used filters for translation `{{ 'some text' | translate }}`, but text-directives can give you more, for example - receive result from server/google-translate.

> Is there support for ajax calls built in?

alight.f$.ajax for inner purpose, but I prefer to use jQuery.get/post.

**Comment by dev-rke** [comment]
> > How to autostart the bootstrap correctly? In jsfiddle i have problems to get it started (i used al-app on the container div), i can only call the bootstrap method manually to get it running.
> 
> For jsfiddle I usually set option "no wrap - in head" - it launches my code before start.

"no wrap - in head" was the missing configuration option.

> > Is there support for ajax calls built in?
> 
> alight.f$.ajax for inner purpose, but I prefer to use jQuery.get/post.

Would it be possible to document such inner methods? Or do you prefer to keep them "hidden" from the developer to have the ability to change them?

Thank you for your answers, i try to migrate my current project now to Angular Light. :-)

I just take a look to your personal cv on your website and i see you started using Basic. I also started  by using Visual Basic and i think Basic might be a reason why we both like CoffeeScript. ;-)

Thanks for your time!

**Comment by lega911** [comment]
> alight.f$

I'm not going to change it, but it doesn't look as well as jQuery.  `$(element).addClass('one') vs f$.addClass(element, 'one')`, on the other hand f$ is much faster than jQuery.
