### ISSUE TITLE
Namespace with #app not working (0.12)

### ISSUE THREAD

**Issue by sanzstez** [lega911/angular-light#233]
Hello!
I am using latest version of AL (0.12), but have issue with namespacing:
In this example everything works fine: http://jsfiddle.net/lega911/93Ahp/  (I suggest that some older version of AL?)
But when i replaced source of AL to 0.12 version, I got some some errors in console and app crashed http://jsfiddle.net/93Ahp/12/
Please help :) Thanks for your great work!

**Comment by lega911** [comment]
Hello!
It was depricated, in 0.12 you can use bootstrap or bind, to bind separate elements.
e.g. bind all elements with class 'app': http://jsfiddle.net/lega911/3mx4bzmr/

**Comment by sanzstez** [comment]
Thanks for answer! So I can use something like syntax to bind app blocks for same controller?
```
<div al-app="controller"> Foo </div>
<div al-app="controller"> Bar </div>
```

**Comment by lega911** [comment]
In 0.12 controller makes isolated scope, but seems you want to have the same scope, there is no builtin way to do this, but you can use bootstrap/bind for this, previous example.

**Comment by sanzstez** [comment]
Thanks! It's a way for my case.
