### ISSUE TITLE
Error in latest precompiled alight.js using bower

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#24]
Hi,

i have problems using the latest precompiled alight.js file using bower (currently version 0.8.4).
Try the following example:

``` html
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="index.css"/>
    <script type="text/javascript" src="http://angularlight.org/bin/alight_0.8.last.min.js"></script>
    <!--<script type="text/javascript" src="bower_components/alight/alight.js"></script>-->
</head>
<body>
    <div id="app" data-al-controller="AppController as app">
        <input type="text" data-al-value="app.name" />
        {{name}}
        <button data-al-click="app.onClick()">click</button>
    </div>
    <script type="text/javascript" src="index.js"></script>
</body>
</html>
```

``` coffeescript
class AppController
    name: "test"
    onClick: ->
        console.log @name

alight.controllers["AppController"] = AppController

alight.directives.data = {}
for name,dir of alight.directives.al
    alight.directives.data["al" + name[0].toUpperCase() + name.substr(1)] = dir

alight.bootstrap document.getElementById "app"
```

Using the latest binary from angularlight.org works without problems, but using the precompiled file using bower throws the following exceptions:
"Error in directive: data-al-controller" Object { value: "AppController as app", env: Object, scope: Object, element: <div#app> } alight.js:6:26363
"Controller isn't found: AppController as app"

Just FYI: i compiled index.coffee to index.js.

Any ideas?

**Comment by lega911** [comment]
0.8.4 doesn't support controller as syntax, I updated bower version to 0.8.8, now it should work.

**Comment by dev-rke** [comment]
Thank you, it works. :-)
