### ISSUE TITLE
Unique directives for each ChangeDetector

### ISSUE THREAD

**Issue by Ni55aN** [lega911/angular-light#248]
I use version 0.14. It does not work $ns, and I can not use direct directives either, because the symbol "!" is not allowed at the end of tag name (Pug simply uses it for its own purposes and trims it).

I make the binding as follows:
```
function createInstance(){
var mydata = ...
var cd = alight.ChangeDetector();

 /// ...
alight.directives.al.node = function(...){
  // here I need to use "mydata",  but when creating a new instance, the directives are overridden
}

alight.bind(cd, el);
}
```

For each bind() there must be directives with unique data (in my case I pass `this`)
How can I pass in the directives unique data used by different `bind()`?

**Comment by Ni55aN** [comment]
Using `&attributes({'node!':''})` added attributes for direct directives, but got another problem: the error `Directive not found: node!` occurs if one of the variables in the template matches the name of the directive

```
<div al-repeat='node in editor.nodes'>
<a node!></a>
</div>
```
Of course I can rename directives, but it would be better to have a more obvious solution

**Comment by lega911** [comment]
$ns was deprecated in 0.14
alight.directives is place for "global" directives per alight (per instance).

I didn't get what exactly you try to do, so I made a few examples:
https://jsfiddle.net/myo7aa6q/ - the same directive, but different data for different elements
https://jsfiddle.net/hj6sa0et/ - different data with own directives inside
https://jsfiddle.net/9Lajz39g/ - clones of alight
https://jsfiddle.net/j5pr2dy6/ - one of the way to change syntax ( changed directive! -> @@@directive )

**Comment by Ni55aN** [comment]
@lega911 tranks, but how to use ChangeDetector with `alight()` ? I need to call `scan()` from outside

**Comment by lega911** [comment]
var changeDetector = alight(element, data);

**Comment by lega911** [comment]
or https://jsfiddle.net/tozxLpc6/

**Comment by Ni55aN** [comment]
Thank you!
