### ISSUE TITLE
al-disable, al-enable at alight 0.14

### ISSUE THREAD

**Issue by lichutin** [lega911/angular-light#250]
Hello!

Are there "al-disable" and "al-enable" directives at alight 0.14? I'm unable to use it, browser gives me an error "Directive not found: al-enable" or "Directive not found: al-disable".
Is that a bug / build problem? (I've seen that al-disable and al-enable had been moved to "compatibility" namespace at coffee-script files.

You can look at code [here](http://jsfiddle.net/ej80e9r4/8/):

Thank you.

**Comment by Ni55aN** [comment]
This version uses a different style for presenting directives:

al-directiveName -> :directiveName
al-on.eventName -> @eventName

Need to change in your example:
`al-disable` to `:disabled`
`al-checked` to `al-model`

http://jsfiddle.net/ej80e9r4/9/
