### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by nin-jin** [lega911/angular-light#251]
http://angularlight.org/

**Comment by lega911** [comment]
Да, я решил "остановить" проект, перенесу сайт на github-page если будет свободное время.
Я получил хороший опыт и теперь я знаю что мне нужно от фреймворка, сделаю alight 2 (так же - если будет свободное время).

**Comment by Ni55aN** [comment]
@lega911 есть какие-то требования к фреймворку, которые не покрывает Vue.js и отсутствует возможность впилить их в виде плагина?

**Comment by lega911** [comment]
@Ni55aN я препочитаю отслеживание на основе dirty-checking, vue работает как "observable", сейчас из dirty-checking, вроде как, есть только ангуляры 1-7, а они монструозны.

**Comment by Ni55aN** [comment]
@lega911 а как на счет быстродействия с dirty-checking?

**Comment by nin-jin** [comment]
Чем же dirty checking лучше?

**Comment by lega911** [comment]
У dirty-checking (DC) проблем с производительностью нет (средний ноутбук обрабатывает более 15Млн простых ватчей в сек), а по тестам он в топе.

Лучше тем что не нужно возится с "compound" - это костыль, а не фича, как её преподносят. Не нужно вручную строить цепочки взаимосвязей, т.е. он проще и ближе к языку.
Можно "отслеживать" совершенно любые значения в отличие. Он не портит отслеживаемый объект (модель), vue например подменяет все на проперти, а если подменить не может, то отслеживание не работает, отсюда вытекает, что само изменение модели, относительно, гораздо медленне т.к. при изменении идет вызов обработчика, когда с DC просто меняется значение как есть, хотя это мелочь.
Ещё в vue как-то трешево создавались локальные переменные для v-for и подобных, хотя пользователей не всегда заботит, что там под капотом.
Это то что вспомил, думаю при использовании ещё пачка минусов наберется.

Конечно у DC есть свои минусы - нюансы (иначе бы его везде использовали).

**Comment by nin-jin** [comment]
Давайте лучше сравним не на "среднем ноутбуке", а на "массовой мобиле". И не операцию сравнения в цикле, а полноценную реализацию с функциями вычисления значения, функциями сравнения и функциями реакции на изменения. Есть такие бенчмарки?

Что такое compound?

**Comment by lega911** [comment]
> Что такое compound?

Я имею ввиду computed (мне кажется в каких-то фреймворках оно называлость compound)
На "массовой мобиле" (новая от 80$) работает прекрасно, я делал андройд приложение alight + cordova.

Из тестов наверное только [этот](http://mathieuancelin.github.io/js-repaint-perfs/) остался с alight (старой версии) **70-100fps**, а у vue2 тут **50-70fps**

**Comment by nin-jin** [comment]
ФПС выше частоты экрана не имеет никакого смысла. Но я говорил именно про заявление о 15кк, а не о фпс фреймворков, производительность которых зависит от кучи факторов.
