### ISSUE TITLE
feature request: directive with controller

### ISSUE THREAD

**Issue by vird** [lega911/angular-light#26]
There was possible in angular make directive with controller by default.
suggested usage:
alight.directives.al['dirname'] =
  template : "<span>some html</span>"
  controller: "dirname"
alight.controllers.dirname = (scope)->

instead of 

alight.directives.al['dirname'] =
  template : "<span al-controller='dirname'>some html</span>"
alight.controllers.dirname = (scope)->

**Comment by lega911** [comment]
Why not:

```
alight.directives.al['dirname'] = {
    template: 'some.html',
    controller: function(scope) {}
}
```

Anyway you can extend Angular Light for self, look this [example](http://plnkr.co/edit/txA6N8H7pjUNtIqduzLa?p=preview), you need make own preprocessor, file ext.js

**Comment by lega911** [comment]
If I understand right, you want something like [this](http://plnkr.co/edit/pQ0XX6p6xOmHYV6b2P4K?p=preview)

**Comment by vird** [comment]
```
alight.directives.al['dirname'] = {
    template: 'some.html',
    controller: function(scope) {}
}
```

not working for me. See
http://plnkr.co/edit/8yuGMO5L7vB3sIhKUAki?p=preview

But your recipe with directivePreprocessor is exactly what i seek.

**Comment by lega911** [comment]
I fixed your [example](http://plnkr.co/edit/csnqEJaCyCpVJ8XaZm1D?p=preview), also you can use "init" or "link", they have scope too:

```
alight.directives.al['dirname'] = {
    template: 'some.html',
    init: function(element, value, scope) {},
    link: function(element, value, scope) {}
}
```
