### ISSUE TITLE
ngModel mimic. al-value in nested directive + custom controller

### ISSUE THREAD

**Issue by vird** [lega911/angular-light#27]
I am goint to import more stuff from angular to angular light.
How it's time for ngModel for custom tags.
I have some kind of this case
http://plnkr.co/edit/FNrXvK7sYAn5r0H9X2YZ?p=preview
I want use ngModel analog, but instead nested scope is just copy of parent scope.
I can make new scope with alight.Scope()
But how can i execute al-value argument?

**Comment by lega911** [comment]
I didn't understand your aim, but I made some [changes](http://plnkr.co/edit/eJXNMZ37uveKqr0IKw2g?p=preview).

if you want new child scope for directive, you can set prop 'scope' ([source](https://github.com/lega911/angular-light/blob/master/alight/core.coffee#L143) of this preprocessor):

```
alight.directives.al.nested = {
    scope: true, // or scope: 'isolate', - it makes new child scope
}
```

You can interrupt directive `al-value="val"` with

```
var nameOfKey = env.takeAttr('al-value');
```

al-value works with input/select well, and I would not mutated al-value, you can make al-model, it has not existed yet.

**Comment by lega911** [comment]
> if you want new child scope for directive, you can set prop 'scope' 

Or equivalent code, manual making a scope:

```
alight.directives.al.nested = {
  init: function(element, exp, parentScope) {
    // make new child scope
    var scope = parentScope.$new();  // or .$new(true) for isolated-scope

    alight.applyBindings(scope, element);  // do binding scope to element

    return {owner: true} // tell AL to stop binding process for current element, because we will do it "by hand"
  }
}
```
