### ISSUE TITLE
How to watch parent node events

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#33]
Hi,

i try to integrate CodeMirror as directive, but i have to fire a refresh event when showing a hidden codemirror instance due to design issues in CodeMirror.

I tried to hook into the hide directive, but i think this is a wrong approach, because it won't bubble the events down to my textarea.
So a better approach might be to watch the parent elements visibility state or to hook into parent events.

Simplified example

``` html
<div data-al-hide="myscope.hide">
<textarea data-al-codemirror="myscope.codemirrorOptions"></textarea>
</div>
```

I need a callback in my codemirror directive when the div gets visible.

Any ideas how to implement that?

**Comment by lega911** [comment]
I think it is wrong behavior of codemirror, you can use **al-ifnot** instead of **al-hide**, it recreates directives and dom, [example](http://jsfiddle.net/lega911/3g9Lj8vz/).

**Comment by dev-rke** [comment]
It just works! Thank you!
Yeah, you're right, CodeMirror is not perfect at all.

After your given example now i understand the following on http://angularlight.org/doc/directives/:

```
Other
    A way to redraw bind-once directives: Example
http://jsfiddle.net/lega911/wRA7L/
```

The first time i saw that i did not understand that this was based on the al-if / al-ifnot directive.
It would be great if this behaviour could be pointed out in the docs a bit more extensive.

I like that you save your examples on the example page, it helps a lot. :-)
