### ISSUE TITLE
Minor improvements in alight.f$ rawAjax method

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#36]
Hi,

it would be great to improve the rawAjax method of alight.f$ with the following to allow sending data, e.g. form data:

``` javascript
var request = new XMLHttpRequest();
request.open(args.type || 'GET', args.url, true, args.username, args.password);
for(var i in args.headers) request.setRequestHeader(i, args.headers[i]);
request.send(args.data || null);
```

as well as the jQuery fallback:

``` javascript
$.ajax({
  url: args.url,
  type: args.type || 'GET',
  headers: data.headers || {},
  data: args.data,
  username: args.username,
  password: args.password
})
```

This allows
- custom request headers
- payload
- http authentication
  and would prevent including another big javascript library or writing many lines of redundant code.

More complex structure does it not handle, but i think it is a useful improvement to allow basic communication with a server.

Questions:
- why is f$ written in javascript and not in coffeescript?
- do you prefer github pull requests for such minor code changes?

**Comment by lega911** [comment]
[Done](https://github.com/lega911/angular-light/commit/4ca64c9990bd03cbf11904a6916efa73374fe573).
I thought, it was going to have different tricks which could look bad in CS, but I was wrong, CS is suitable for fquery.
Any way is ok, you can send "pull requests" if you want.

**Comment by dev-rke** [comment]
Thank you.
Can you release your changes for the bower repository please? :-)

Optionally: might it be possible to automate the release process?

**Comment by lega911** [comment]
done.
alight bower is built by one click, i don't do this every time because it is like dev-version.
