### ISSUE TITLE
JSFiddle / markdown example

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#37]
Hi,

i just built an example how to use markdown by defining a custom filter:
http://jsfiddle.net/kctqwdqj/9/

If you want you can place it on your examples page.

**Comment by lega911** [comment]
Thank you, I added it, interesting sample, but it's can be heavy, because filters are called on every scan loop. Markdown as directive would be more optimal.

**Comment by dev-rke** [comment]
Thanks for your hint, i extended it to also use a directive:
http://jsfiddle.net/kctqwdqj/10/

**Comment by lega911** [comment]
My [variant](http://jsfiddle.net/lega911/pLh7uu8r/) of the directive

**Comment by dev-rke** [comment]
Great! I will use your implementation, it's much shorter. :-)
