### ISSUE TITLE
core.coffee / javascript?

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#38]
Hi,

i just stumbled over the following line in core.coffee@734:

``` coffeescript
f1 = func
`func = function() { var __ = f1.apply(this, arguments); return '' + (__ || (__ == null?'':__)) }`
```

It should be the same to write:

``` coffeescript
f1 = func
func = ->
    __ = f1.apply this, arguments
    "" + (__ or (if __ is null then '' else __))
```

Please correct me if i am wrong.

**Comment by lega911** [comment]
`if __ is null then '' else __`
we need `__ == null`, not `__ === null`, because `null==undefined`

**Comment by dev-rke** [comment]
Yeah, i thought already about that.
But then you could simplify the code:

``` coffeescript
f1 = func
func = ->
    __ = f1.apply this, arguments
    "" + (__ or "")
```

**Comment by lega911** [comment]
Then we miss number 0

**Comment by dev-rke** [comment]
``` coffeescript
f1 = func
func = ->
    __ = f1.apply this, arguments
    "" + (if (__ or __ is 0) then __ else "")
```

Is it relevant to catch all possible cases, e.g. if it is false etc.?

**Comment by lega911** [comment]
Yes, true and false give us text "true, false"

**Comment by dev-rke** [comment]
Ok, just crawled through the coffeescript docs, we could use the existential operator, @see http://coffeescript.org/#operators and scroll down to existential operator.

``` coffeescript
f1 = func
func = ->
    __ = f1.apply this, arguments
    "" + (__ or __ ?= '')
```

Any problems left? :-)

**Comment by dev-rke** [comment]
Wohoo, every iteration gives better results and my knowledge about CS improves. ;-)

``` coffeescript
f1 = func
func = ->
    __ = f1.apply this, arguments
    "" + (__ or (__ ? ''))
```

compiles to

``` javascript
f1 = func;
func = function() {
  var __;
  __ = f1.apply(this, arguments);
  return "" + (__ || (__ != null ? __ : ''));
};
```

**Comment by lega911** [comment]
Yes, it gives right result. [fixed](https://github.com/lega911/angular-light/commit/fa54c9ebf908e3ec108938e4959db3462eac97d3).
