### ISSUE TITLE
Setting array to {} does reset form values

### ISSUE THREAD

**Issue by Rastishka** [lega911/angular-light#39]
http://jsfiddle.net/Rastishka/9x4jpfq3/5/

Setting array to {} does reset form values inside this array.

**Comment by lega911** [comment]
[fixed](https://github.com/lega911/angular-light/commit/3df58ca206c62fc9305edc53dc7bb0afea727b4a).
Also, you don't have to call $scan there (but you can if you want), because AL do it after al-click, [example](http://jsfiddle.net/lega911/a8z3L1L2/).
