### ISSUE TITLE
Refactoring core.coffee / javascript? Part 2

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#41]
Hi,

core.coffee@366-383 translated to pure CS:

``` coffeescript
return @ if @ instanceof Scope
conf = conf || {}
if conf.prototype
    Parent = ->
    Parent:: = conf::
    parent = new Parent()
    proto = Scope.prototype
    for k of proto
        parent[k] = proto[k]
    NScope = ->
    NScope:: = parent
    scope = new NScope()
else
    scope = new Scope()
```

compiles to

``` javascript
if (this instanceof Scope) {
  return this;
}

conf = conf || {};

if (conf.prototype) {
  Parent = function() {};
  Parent.prototype = conf.prototype;
  parent = new Parent();
  proto = Scope.prototype;
  for (k in proto) {
    parent[k] = proto[k];
  }
  NScope = function() {};
  NScope.prototype = parent;
  scope = new NScope();
} else {
  scope = new Scope();
}
```

I think about using classes would make the code more CS convenient and easier to understand.
Give me some time, please let the ticket stay open a few hours. ;-)

**Comment by dev-rke** [comment]
Is it anywhere required to define a conf object in constructor (e.g. for planned features or config injection)?
I did not find any calls to Scope() method that contain parameters also the docs do not show any hints for this conf object.
So i think we could leave out the whole part and simplify to

``` coffeescript
Scope = () ->
    return @ if @ instanceof Scope
    conf = {}
    scope = new Scope()
```

Unit tests are fine with this change.

What do you think?

**Comment by lega911** [comment]
It's used [here](https://github.com/lega911/angular-light/blob/fa54c9ebf908e3ec108938e4959db3462eac97d3/alight/core.coffee#L1207)

**Comment by lega911** [comment]
[example](http://jsfiddle.net/lega911/x04sxwme/)

**Comment by dev-rke** [comment]
Ok. What do you think about the implementation in my first post?

**Comment by lega911** [comment]
I took [it](https://github.com/lega911/angular-light/commit/50870cc2dafe2cb7cbb26a19cde8158569ebfd41)

**Comment by dev-rke** [comment]
I thought about refactoring the code to the following:

``` coffeescript
return @ if @ instanceof Scope
conf = conf || {}
if conf.prototype
    class Parent extends conf
    parent = new Parent()
    proto = Scope.prototype
    for k of proto
        parent[k] = proto[k]
    class NScope extends parent
    scope = new NScope()
else
    scope = new Scope()
```

But....

``` coffeescript
class Parent extends conf
```

would extend conf only if its a real prototype (there is already the working condition).
The code is not tested, so if you want to use it, do it at your own risk.

Another approach might be to refactor all root objects to classes, but this might also increase memory consumption.

If you do not like it, just close this ticket. ;-)

**Comment by lega911** [comment]
I will look at it later, now I'm doing a big change, it is lightweight scopes, which is going to be default, also there will appear base functions watch, compile and the like, which let you make own framework. Angular Light will become a wrapper over this library.

**Comment by dev-rke** [comment]
Ticket is obsolete due to your refactoring @ cdf88f7ce7cd71629823fba49b12b1918bd17547 
Closed.
