### ISSUE TITLE
Drag'n'Drop directive

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#50]
Hi,

might it be possible to integrate drag'n'drop directives into alight by default?
If you would appreciate it, but priorize other things first, i would give it a try to develop it.

If not, might it be useful to create a place, where custom directives can be collected? 
E.g. by creating an additional directives project?

**Comment by lega911** [comment]
It's good idea, I made a [repository](https://github.com/lega911/angular-light-addition) for this, and I have already had some directives to put there, may be in future there will be default and full versions.
