### ISSUE TITLE
Communication between controllers

### ISSUE THREAD

**Issue by dev-rke** [lega911/angular-light#51]
Hi,

how to communicate between controllers?
I use instances using the al-controller-Syntax.

Lets assume a simple example:

``` coffeescript
class MyController
  constructor: (@scope) ->
    @myVar = 'Hello World'

alight.controllers['MyController'] = MyController
```

``` html
<div data-al-controller="MyController as myCtrl1">
</div>
<div data-al-controller="MyController as myCtrl2">
</div>
```

Now i have two instances. But how to communicate between them correctly?
Using a shared variable might be an option, but i dont like that approach.
Does alight provide any method to get the current controller instances?

I tried it using 

``` coffeescript
ctrl = alight.getController("MyController", @scope)
```

but i get just errors, it seems i provide the wrong scope when accessing methods of the ctrl object.

Any ideas how to get this solved? What am i doing wrong?

**Comment by lega911** [comment]
There are a lot ways, for example [pubsub](http://jsfiddle.net/lega911/0r3o7bju/), [shared-var](http://jsfiddle.net/lega911/t945r1gh/)..., it depends on your architecure, also there are a lot of ready libs.

**Comment by lega911** [comment]
`ctrl = alight.getController("MyController", @scope)`
it just gives a function controller (from alight.controllers or scope.$ns)

**Comment by dev-rke** [comment]
Great! Didn't know the pubsub pattern as a 'pattern', it seems to be quite useful.
I think it is helpful to communicate between objects globally.
I think also it would make sense to implement it into the alight utils, it makes prototyped communication and the handling between multiple objects much easier.
Btw.: why is the namespace called "utilits" and not "utils"?

I translated and extended a small implementation by David Walsh to CS, you can use it, if you want:

``` coffeescript
class PubSub
    @topics: {}
    @subscribe: (topic, listener) ->
        @topics[topic] = [] if not @topics[topic]
        index = @topics[topic].push(listener) - 1
        remove: -> delete @topics[topic][index]
    @remove: (topic) -> delete @topics[topic]
    @publish: (topic, info, cb = ->) ->
        return if not @topics[topic]
        for item in @topics[topic]
            item(if info != undefined then info or {})
        cb()
```

Example:

``` coffeescript
activeTab = null
PubSub.subscribe 'switchActiveTab', (target) =>
    activeTab = target
```

``` coffeescript
PubSub.publish 'switchActiveTab', 'Home', ->
    console.log "switched to Home"
```

For further details see: http://davidwalsh.name/pubsub-javascript

**Comment by lega911** [comment]
There are a few kinds of pubsub, with different features, every project can have own/ specific implementation of pubsub, so I think AL shouldn't enforce to use specific version.
