### ISSUE TITLE
Directives is not work in scope.$evalText?

### ISSUE THREAD

**Issue by adw0rd** [lega911/angular-light#53]
Hello, I want to make modal window based on twitter bootstrap, current prototype:

```
var product_template = $.ajax({url: '/static/views/products/quickview.html', async: false}).responseText;
$('#product-details-modal').on('show.bs.modal', function (event) {
    var id = $(event.relatedTarget).data('id');
    var modal = $(this);
    $.get('/p/f/' + id + '/', {}, function (product) {
        var scope = alight.Scope();
        scope.product = product;
        var html = scope.$evalText(product_template);
        modal.html(html);
    });
});
```

The variables in the template output, but the directive (eg al-if, al-show, al-repeat) do not work. What am i doing wrong?

Example of "/static/views/products/quickview.html"

```
<div class="modal-dialog">
    <div class="modal-content">
        <h1>{{ product.name }}</h1>
        <div al-repeat="item in product.photos">
            <a>
                <img class="img-responsive" al-src="{{ item.photo_url }}">
            </a>
        </div>
    </div>
</div>
```

**Comment by lega911** [comment]
Hello.
You need to use `alight.applyBindings(scope, modal[0]);`, it binds scope to the DOM.
[Here](http://angularlight.org/tutorial/bindings.html) you can see a few ways to bind.
I've made [an example](http://plnkr.co/edit/ZLk8GI0NDhe2aLgnJf5N?p=preview) for you.
But I prefer to use it as a separate object, you can call `alight.openModal('dialog.html');` from everywhere, [example](http://plnkr.co/edit/dfrFwbLcy8cANpK6Rok0?p=preview).

**Comment by adw0rd** [comment]
Thanks, modal window works very well
