### ISSUE TITLE
[Bug] Invalid text directives behavior in IE11

### ISSUE THREAD

**Issue by 110yd** [lega911/angular-light#56]
Here's simple demo of combining al-repeat with text directive in style attr.
http://plnkr.co/edit/Zlbd1OXxFQgz5xcDw9U2

Google Chome 42.0.2311.152 m
![alight-notbug](https://cloud.githubusercontent.com/assets/4981571/7685029/6c6abe2a-fd93-11e4-8961-fd2539e81aa4.PNG)

Internet Explorer 11.0.10011.0
![alight-bug](https://cloud.githubusercontent.com/assets/4981571/7685011/4eafbc6e-fd93-11e4-830a-e692e14a0508.PNG)
![alight-bug2](https://cloud.githubusercontent.com/assets/4981571/7685086/e0e89100-fd93-11e4-9e3b-68f54b80cad9.PNG)

**Comment by lega911** [comment]
IE11 removes style attributes before Angular Light starts. AngularJS has the same problem [link](http://stackoverflow.com/questions/23732263/angular-js-works-in-chrome-but-not-ie-11) [link2](https://github.com/angular/angular.js/issues/2186), and Polymerjs and other.
It means you need use al-style (version 0.8.last has it) or something like this. [example](http://plnkr.co/edit/8nyoO1NtaElRxA2baNQ8?p=preview)

**Comment by 110yd** [comment]
Thanks. I think it's useful.
Maybe it should be mentioned in the documentation?
