### ISSUE TITLE
Analog $scope.$apply 

### ISSUE THREAD

**Issue by sunchess** [lega911/angular-light#57]
How can I reload $scope by Angular Light like AngelarJS $scope.$apply?
I have code

function fieldSetCtrl($scope) {

  $scope.append = function() {

```
$.ajax({
  method: "POST",
  url: Routes.fieldsets_path(),
  data: $('#new_fieldset').serialize()
})
.success(function( msg ) {
  $scope.list.push({ title: $scope.title });
  $scope.title = '';
})
.error(function(msg, state) {
  json = JSON.parse(msg.responseText)
  $scope.errors = json['errors'];
});
```

  };
I try to set the $scope.errors but not have effect. Any ideas? 

Thanks.

**Comment by erickskrauch** [comment]
``` js
$scope.scan()
```

**Comment by lega911** [comment]
``` js
$scope.errors = json['errors'];
$scope.$scan();
```

Also you can give a function to $scan(callback), the function is executed when $scan finish work.

``` js
$scope.$scan(function() {
  // $scan finished
});
```

**Comment by sunchess** [comment]
Thanks, It should be in the man. I did not find.
