### ISSUE TITLE
? control priority of directives from html

### ISSUE THREAD

**Issue by lega911** [lega911/angular-light#64]
`<div al-init_9="..." al-click_5="..."></div>`

`<div al-init.9="..." al-click.5="..."></div>`

**Comment by dev-rke** [comment]
These priorities are only relevant at binding time, right? When is it needed to define it by the developer?

**Comment by lega911** [comment]
``` html
<div al-init="X=5" al-ctrl="rootCtrl" al-repeat="i in X">
```

al-repeat has the biggest priority, it goes first, what if you need al-init/al-ctrl goes first?

**Comment by dev-rke** [comment]
Priority is per element, right?
First init then Ctrl then repeat.
init to define variables, Ctrl to create scope, repeat to use scope.
This should be by default.

**Comment by lega911** [comment]
> Priority is per element, right?

yes

> First init then Ctrl then repeat. This should be by default.

Then "X=5" wouldn't be in rootCtrl (it would be rootCtrl.$parent.X), so al-repeat wouldn't reach X.
Next example: what if you have a list of users and you need to use userCtrl for everyone:

``` html
<div al-repeat="user in userList" al-ctrl="userCtrl">
```

You couldn't do this if al-ctrl was first.

**Comment by dev-rke** [comment]
Just an idea: reading and using the order of the attributes in an element? This makes more sense for me than adding modifiers.

**Comment by lega911** [comment]
> the order of the attributes in an element

It was first what I tried, browsers don't keep the order, and different browsers can give you different result.

**Comment by dev-rke** [comment]
How AL or AL2 solve this?

**Comment by lega911** [comment]
> How AL or AL2 solve this?

Angular.js 1 works the same, every directive has a priority.
I don't know what approach is used in A2, but A2 can use the order of attributes, because, A2 uses own html-parser (which understands non standard attributes).
