### ISSUE TITLE
? al-repeat="@ in list"

### ISSUE THREAD

**Issue by lega911** [lega911/angular-light#76]
it will give direct access to content
var users = [{name: 1, size: 2}]

```
<div al-repeat="@ in users">
    {{name}} - {{size}} / {{$parent.list.length}}
    <p al-click="name=5"></p>
    <p>{{$parent.methodFromParent()}}</p>
</div>
```

**Comment by dev-rke** [comment]
I like this.
I would like to see this more like a [destructuring assignment](http://coffeescript.org/#destructuring) similar as coffeescript does.
This would allow to define own alias-directives to give the developer more flexibility with data structures.

**Comment by lega911** [comment]
It was easier to make for 0.11 version, because 0.11 doesn't have Scope.
For new version it will have a problems, there are few ways to do this:
1) use items from list (users)
2) clone items
3) clone items and use $parent as prototype
4) use item from list and use $parent as prorotype

Problems:
1) if I use items from list, then they will not have $parent, because an item doesn't have it, or I should 
2) problem from 3
put $parent in every item of list :(
3) if I clone item, then `al-click="name=5"` will not work, because "name" will be placed in cloned item.
4) not every browser supports changing prototype (also it can work slowly)

probably, the best way is 3 (or 2), but if you will want to change name, you will should do: `al-click="users[$index].name=5"`

> This would allow to define own alias-directives to give the developer more flexibility with data structures.

What do you mean? Give an example.
